### ISSUE TITLE
Error: Validation Failed.

### ISSUE THREAD

**Issue by siwifttiger** [gitalk/gitalk#103]
好多页面下的评论都显示如图所示的错误，这是为什么呢？
![image](https://user-images.githubusercontent.com/9268647/35900238-d0faea0c-0c0b-11e8-9441-4961bcba78c4.png)

**Comment by hushhw** [comment]
同

**Comment by booxood** [comment]
与 #102 应该是一样的问题，去那个 issue 讨论吧
