### ISSUE TITLE
微信webview中显示Error: Validation Failed

### ISSUE THREAD

**Issue by Justice-love** [gitalk/gitalk#104]
使用的是URL作为issue的tag来进行关联的，在微信中打开会默认增加一些请求参数，导致使用URL无法关联issue而会重新创建issue。

由于github中issue的tag限制50个字符，加上微信自动增加的请求参数，字符数超出限制，一般都会出现Error: Validation Failed异常。

建议 @booxood 使用request URI作为tag进行关联

**Comment by booxood** [comment]
使用 `request URI` 还是有可能会超过50个字符，参考 #102 讨论里提到的一些方法吧。

**Comment by Justice-love** [comment]
我的意思是，既然是id属性，就应该具备id的特性，即同一页面的id无论在哪打开都是不变的。 现在的情况是PC端和微信端的默认ID会不一样。
至于50个字符的限制那是后话，先得保证ID不变。
