### ISSUE TITLE
"GET /gitalk.js.map HTTP/1.1" 404

### ISSUE THREAD

**Issue by iShawnWang** [gitalk/gitalk#105]
![2acd53b7-4746-489d-90b2-25e1bc66f199](https://user-images.githubusercontent.com/20266594/36046512-22b7deae-0e14-11e8-8c23-81cdc11d7877.jpg)

因为这里有配置 sourcemap, chrome 调试会请求这个 sourcemap, 而 node 后端并不知道 gittalk.js.map 在 node_modules 文件夹中, 怎样能传递 sourceMap 不让他报 404 呢 ?

**Comment by booxood** [comment]
@iShawnWang  `gittalk.js` 是放在哪里？把 `gittalk.js.map` 与 `gittalk.js` 放在同一个目录下？

**Comment by iShawnWang** [comment]
就是 npm install 的 gittalk, 在 node_modules/gittalk/文件夹下面有 `gitalk.js.map`, 但是 express server 怎么配置来让 chrome 访问这个 sourcemap 呢 ?

**Comment by booxood** [comment]
> 但是 express server 怎么配置来让 chrome 访问这个 sourcemap 呢 ?

你现在的 express server 配置可以访问到 gitalk.js 吗？

**Comment by iShawnWang** [comment]
自己做着玩的小项目 : 
分前端和后端

前端是 Pug 模板

`index.js` 里面 `import Gitalk from 'gitalk'` 引入 gittalk 然后 webpack 打包一下

后端是 express server, 根据路由渲染不同的 pug 模板... 

这样...

**Comment by booxood** [comment]
这个问题不会影响你的使用，先关闭 issue 了。

如果你还是希望解决，最好能提供一个说明这个问题的 demo 。
