### ISSUE TITLE
未找到相关的 Issues 进行评论  请联系******* 初始化创建 怎么解决

### ISSUE THREAD

**Issue by wanghaodi** [gitalk/gitalk#109]

**Comment by booxood** [comment]
@wanghaodi 配置贴出来看下

**Comment by wanghaodi** [comment]
已经解决，问题的原因同#102 ：label太长导致的无法评论

**Comment by ab-Alex** [comment]
@war   同样的问题，怎么解决的？？？

**Comment by liugezhou** [comment]
我也出现了这样的问题。。。

**Comment by sucls** [comment]
f各种配置都检查了就是不行！！！
![image](https://user-images.githubusercontent.com/53465031/219943299-ec5fbbde-53ac-45c9-a663-d092aa1b979d.png)
![image](https://user-images.githubusercontent.com/53465031/219943315-7b0f948c-a6f5-4c3a-bc33-01ab4d286b9e.png)
不知道与下面那个提示有没关系

**Comment by MillyHerrington** [comment]
यह सब चीनी क्या है? आप क्या कहना चाहते हैं?
