### ISSUE TITLE
初始化过的页面切换其他页面后返回报错Error: no access token

### ISSUE THREAD

**Issue by hsqzggg** [gitalk/gitalk#110]
主页和子页面都添加了脚本，从主页点初始化按钮后评论一句点主页的子页面链接跳转后评论后再返回就一直加载中，提示Error: no access token
主页和子页面都添加代码如下（信息部分保密未填admin和owner一致）：
`  <div id="gitalk-container"></div> <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script> <script> const gitalk = new Gitalk({
  clientID: 'Github Application Client ID',
  clientSecret: 'Github Application Client Secret',
  repo: 'Github repo',
  owner: 'Github repo owner',
  admin: ['Github repo owner and collaborators, only these guys can initialize github issues'],
  // facebook-like distraction free mode
  distractionFreeMode: false
})

gitalk.render('gitalk-container') </script>`

**Comment by booxood** [comment]
@hsqzggg `id` 有配置吗？

**Comment by LichFaker** [comment]
同遇到该问题，初始化后的`Issue`中会带有`post`的链接，通过该链接进入页面会提示: `Error: no access token`。重新刷新则显示正常， 区别在于前者多了`?code=xxxx`

**Comment by booxood** [comment]
@LichFaker `?code=xxxx` 是授权登录跳转回来的时候带上的，post的链接上不应该有 `?code=xxxx` ，code 应该是登录用过一次就失效了。

**Comment by booxood** [comment]
先关闭了，还有相同问题再打开。

**Comment by Muska-Ami** [comment]
相同问题，已配置参数正确，之前是正常的
