### ISSUE TITLE
能否考虑适配添加夜间主题的评论样式

### ISSUE THREAD

**Issue by mjd507** [gitalk/gitalk#111]
我的博客地址：https://mjd507.github.io/
因为博客是夜间主题，而gitalk 在白色主题中显示比较友好
所以能否添加一套夜间主题的样式？

**Comment by booxood** [comment]
可以考虑添加。

不过针对自己的博客建议自己自定义一下样式比较好。

**Comment by CoderMing** [comment]
@mjd507 [我的博客](https://coderming.com)尝试适配了以下夜间模式，具体你可以参考下我的博客项目中的代码：https://github.com/CoderMing/blogsue

**Comment by mjd507** [comment]
@CoderMing 谢谢，我之前稍微修改了夜间样式，看上去还凑合

**Comment by ATommyGirl** [comment]
> @mjd507 [我的博客](https://coderming.com)尝试适配了夜间模式，具体你可以参考下我的博客项目中的代码：https://github.com/CoderMing/blogsue

你好，请问 评论预览 时的文字颜色怎么改呀，前端完全不懂 😂
