### ISSUE TITLE
Error: Not Found.

### ISSUE THREAD

**Issue by KiyomiHan** [gitalk/gitalk#112]
是这样的，我的blog 不是搭载在github上的
此时repo 应该填写什么呢？

**Comment by colingpt** [comment]
任意你拥有初始化权限的repo即可

**Comment by guokelide** [comment]
出现Error: Not Found.   登录后评论无法提交.

**Comment by shengshuqiang** [comment]
出现Error: Not Found. 登录后评论无法提交.
+1
