### ISSUE TITLE
hexo next 主题配置 gitalk 评论后无法初始化创建 issue

### ISSUE THREAD

**Issue by qhh0205** [gitalk/gitalk#115]
@booxood @lex111 @mamboer 
### 问题描述
我根据[这篇教程配](https://asdfv1929.github.io/2018/01/20/gitalk/)的，过程完全一模一样，但是配完后打开每篇文章（没有报任何错），没有评论框，只有如下 gitalk 提示：
![image](https://user-images.githubusercontent.com/12775142/37871162-f544f54c-3019-11e8-8217-d02b84d686c8.png)
**我点击底下的登录按钮后直接进入 github 博客仓库了，并没有 issue 产生，这是什么原因呢？而且返回页面后还是这样，没有什么变化，一直显示没有相关 issue。。**
*我的 blog 地址：https://qhh0205.github.io/*
### 主要配置
**next 主题文件 gitalk 配置：**
![image](https://user-images.githubusercontent.com/12775142/37871180-79132fec-301a-11e8-9fcb-fdf471a2a998.png)
**layout/_third-party/comments/gitalk.swig 文件：**
```swig
{% if page.comments && theme.gitalk.enable %}
  <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
   <script type="text/javascript">
        var gitalk = new Gitalk({
          clientID: '{{ theme.gitalk.ClientID }}',
          clientSecret: '{{ theme.gitalk.ClientSecret }}',
          repo: '{{ theme.gitalk.repo }}',
          owner: '{{ theme.gitalk.githubID }}',
          admin: ['{{ theme.gitalk.adminUser }}'],
          id: location.pathname,
          distractionFreeMode: '{{ theme.gitalk.distractionFreeMode }}'
        })
        gitalk.render('gitalk-container')
    </script>
{% endif %}
```

**Comment by qhh0205** [comment]
用 Chrome 检查工具看了下，应该是 api 认证失败导致，我看调用 github api 认证失败，但是我仔细检查了下认证的 id 和 secreat key 都没问题啊：
![image](https://user-images.githubusercontent.com/12775142/37871439-648a98ac-3020-11e8-9fff-383ee1070e94.png)
![image](https://user-images.githubusercontent.com/12775142/37871469-14dfb4c6-3021-11e8-956f-4fd5525bdf3c.png)

**Comment by iochen** [comment]
![image](https://user-images.githubusercontent.com/28243989/37871821-2d0182b0-302a-11e8-8e59-5e1764b8201b.png)
填repo名字，不是填地址

**Comment by iochen** [comment]
同时，建议不要使用中文为post文件名，
![image](https://user-images.githubusercontent.com/28243989/37871838-6b089c1a-302a-11e8-9fc6-409c8fce26ff.png)
详见 [https://github.com/gitalk/gitalk/issues/102#issuecomment-363843179](https://github.com/gitalk/gitalk/issues/102#issuecomment-363843179)

**Comment by qhh0205** [comment]
@iochen 
我的仓库的名字就是 ``qhh0205.github.io``
https://github.com/qhh0205/qhh0205.github.io
![image](https://user-images.githubusercontent.com/12775142/37871845-9d056770-302a-11e8-84f0-2a25bfbe2704.png)

**Comment by iochen** [comment]
好吧，是我看错了……看看下一个方案有没有用，我以前就吃过文件名过长的坑

**Comment by qhh0205** [comment]
@iochen 
应该不是文件名过长问题，我刚新建了一个 post，名称为：``test``，这个够短了吧，但是还是同样的问题。
https://qhh0205.github.io/2018/03/25/test/

**Comment by iochen** [comment]
![image](https://user-images.githubusercontent.com/28243989/37871944-03d1db2a-302e-11e8-8459-5ecc10a97cf6.png)
回调地址确认一下

**Comment by iochen** [comment]
![image](https://user-images.githubusercontent.com/28243989/37871955-656590c0-302e-11e8-8805-29ae852b2611.png)
这是我的

**Comment by qhh0205** [comment]
@iochen 
回调地址也是没问题的：
![image](https://user-images.githubusercontent.com/12775142/37871962-b1bf42ea-302e-11e8-8948-6e3136c9ba14.png)

**Comment by qhh0205** [comment]
@iochen 回调地址是博客地址吗？还是仓库地址

**Comment by qhh0205** [comment]
@iochen 非常感谢啊🙏，可以了，是回调地址不对，改成博客地址就 ok 了！！
不过出现之前的老问题了：``Error: Validation Failed.``
就是中文标题导致编码过长的问题，这个现在应该有好的解决方法了吧？
![image](https://user-images.githubusercontent.com/12775142/37872001-c7bbe214-302f-11e8-973f-be8ef1d07172.png)

**Comment by qhh0205** [comment]
@iochen 你好麻烦再请教下，我按照之前的 issue #102 用 md5 加密 id，本地 npm install md5 是成功的。
但是没生效，blog 页面底下评论框都没了，不知道什么原因。。。
blog 地址：http://qhh0205.github.io/
具体配置如下：

{% if page.comments && theme.gitalk.enable %}
  <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
   <script type="text/javascript">
        var gitalk = new Gitalk({
          clientID: '3840ba8c8d80c18be7e3',
          clientSecret: '1b00f2efe5285973c24da9ed9ac895775eacc8ea',
          repo: '{{ theme.gitalk.repo }}',
          owner: '{{ theme.gitalk.githubID }}',
          admin: ['{{ theme.gitalk.adminUser }}'],
          id: md5(location.pathname),
          distractionFreeMode: '{{ theme.gitalk.distractionFreeMode }}'
        })
        gitalk.render('gitalk-container')
    </script>
{% endif %}

**Comment by iochen** [comment]
@qhh0205 将 https://github.com/blueimp/JavaScript-MD5/blob/master/js/md5.min.js 下载放到你hexo的js文件夹中， 然后在配置上方加上`<script src="这里是你的MD5的js的路径"></script>`
就像这样
![image](https://user-images.githubusercontent.com/28243989/37872964-339c82a8-3045-11e8-8e35-f7e59617532c.png)
然后上传测试一下，我自己测试了一下。可以
![image](https://user-images.githubusercontent.com/28243989/37872971-5c5b6952-3045-11e8-93d7-a92ef273baac.png)

**Comment by qhh0205** [comment]
@iochen  非常感谢，又帮我解决了个问题。
我没有本地加载，我选择远程加载了下，我一般把代码片段都保存成了 gist，所以我创建了个 gitst，然后远程引入 js gist 地址。
在此把具体过程详细写下，献给小白朋友们（当然我也是 QAQ）：

### 解决：gitalk 报错 ``Error: Validation Failed.``--MD5 加密 ``id`` 避免 github issue lables 50 字符限制
1. 创建一个github gist 文件保存 https://github.com/blueimp/JavaScript-MD5/blob/master/js/md5.min.js js 源码：
https://gist.githubusercontent.com/qhh0205/78e9e0b1f3114db6737f3ed8cdd51d3a/raw/3894c5be5aa2378336b1f5ee0f296fa0b22d06e9/md5.min.js
2. 将 gist 链接嵌入到 ``layout/_third-party/comments/gitalk.swig`` 文件，嵌入时的 js 链接地址需要注意下：
不能直接写第一步的创建的 gitst 链接地址，需要将 ``gist.githubusercontent.com`` 替换为 ``rawgit.com``。即嵌入地址为: https://rawgit.com/qhh0205/78e9e0b1f3114db6737f3ed8cdd51d3a/raw/3894c5be5aa2378336b1f5ee0f296fa0b22d06e9/md5.min.js
最终 ``layout/_third-party/comments/gitalk.swig`` 配置如下：
```js
{% if page.comments && theme.gitalk.enable %}
  <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
  <script src="https://rawgit.com/qhh0205/78e9e0b1f3114db6737f3ed8cdd51d3a/raw/3894c5be5aa2378336b1f5ee0f296fa0b22d06e9/md5.min.js"></script>
   <script type="text/javascript">
        var gitalk = new Gitalk({
          clientID: '3840ba8c8d80c18be7e3',
          clientSecret: '1b00f2efe5285973c24da9ed9ac895775eacc8ea',
          repo: '{{ theme.gitalk.repo }}',
          owner: '{{ theme.gitalk.githubID }}',
          admin: ['{{ theme.gitalk.adminUser }}'],
          id: md5(location.pathname),
          distractionFreeMode: '{{ theme.gitalk.distractionFreeMode }}'
        })
        gitalk.render('gitalk-container')
    </script>
{% endif %}
```

**Comment by shigithup** [comment]
终于成功了，同无法初始化。我的回调地址一直是github的博客repo名字，但是如果绑定了个性化域名，那么回调地址就要修改为个性化的域名了。。

**Comment by yymfp** [comment]
请问Error: no access token 怎么解决？

**Comment by booxood** [comment]
@guguji5 在本地环境时，可以先改成 localhost:xxxx 测试。

**Comment by Imodel** [comment]
> 终于成功了，同无法初始化。我的回调地址一直是github的博客repo名字，但是如果绑定了个性化域名，那么回调地址就要修改为个性化的域名了。。
applications这个申请的时候，都是个性化域名，_config.yaml配置的是xxx.github.io

**Comment by Mart1nch** [comment]
报错issues are disabled for this repo
![wechatimg80](https://user-images.githubusercontent.com/38450202/52901154-4a722f80-323a-11e9-8764-b730d6123752.jpeg)
setting-features-issues打勾
要考的 敲黑板了！

**Comment by linh47** [comment]
> 妹的，那个oauth 授权必须在你的 homepage url才能授权成功。我在hexo s的localhost环境测了半天

哈哈哈哈我也是在本地服务器测了半天发现登录的时候会调回主页还报错回调不一致，看了半天都是同一个网址一脸懵逼。
部署到github就好了。

**Comment by DogBaoBao** [comment]
> @iochen 非常感谢啊🙏，可以了，是回调地址不对，改成博客地址就 ok 了！！
> ![image](https://user-images.githubusercontent.com/12775142/37872011-f8f243f0-302f-11e8-8fdf-028aa8751824.png)
> 
> 不过出现之前的老问题了：`Error: Validation Failed.`
> 就是中文标题导致编码过长的问题，这个现在应该有好的解决方法了吧？
> 关于 `Error: Validation Failed.` 问题我再参考下 #102
> ![image](https://user-images.githubusercontent.com/12775142/37872001-c7bbe214-302f-11e8-973f-be8ef1d07172.png)

@qhh0205 大兄弟请教下，home page url 和回调地址都是配置成 博客地址吧？如果配置了自己的域名配置成自己域名吗？

**Comment by wsuo** [comment]
> 终于成功了，同无法初始化。我的回调地址一直是github的博客repo名字，但是如果绑定了个性化域名，那么回调地址就要修改为个性化的域名了。。

确实，我也是这个问题，改了域名之后再发布文章之后就发现了这个问题，改了域名这里也要同步修改

**Comment by Allen2021** [comment]
Error: Network Error
--------
repo: '库名 、域名都出错'

**Comment by zzzcat013** [comment]
学习了，终于成功了

**Comment by 46fafa** [comment]
> <script src="这里是你的MD5的js的路径"></script>

![image](https://user-images.githubusercontent.com/92380602/209770416-a4f3d2c2-0c5b-49fe-862c-e90c1861c3b1.png)
![image](https://user-images.githubusercontent.com/92380602/209770449-73dc5c4d-b0ec-4fd8-ae32-bcc89d9c8403.png)
![image](https://user-images.githubusercontent.com/92380602/209770508-5050bdc5-fc0c-4e9a-b717-ee5149d725f6.png)
大佬你好,我参照你给出的步骤,但是结果还是不行,麻烦你帮我看一下那里存在问题吗

**Comment by SinceJack** [comment]
我也遇到了相同的问题，需要注意的是 Homepage URL 和 Authorization callback URL 必须填写 https:// 前缀，http:// 是不行的
