### ISSUE TITLE
文章标题名不能太长（已解决）

### ISSUE THREAD

**Issue by zhebinhu** [gitalk/gitalk#124]
初始化不成功，出现Error: Validation Failed.

文章标题名“CentOS7下使用Systemctl管理服务”不能初始化评论，改成“Systemctl管理服务”就可以。

**Comment by dengqinghua** [comment]
您好, 我也遇到了这个问题, 我的解决方案是:

```javascript
  var gitalk   = new Gitalk({
         // 在这里设置一下截取前50个字符串, 这是因为 github 对 label 的长度有了要求, 如果超过
         // 50个字符串则会报错.
        id: (location.pathname).split("/").pop().substring(0, 49);,  
        distractionFreeMode: true,
        language: language
      });
```

**Comment by zhuSilence** [comment]
更优雅的做法在其他issue里面有提到，采用MD5摘要url的做法，比这种字符串截取要优雅点。

**Comment by dengqinghua** [comment]
md5码当时也考虑过，但是会使得label变成一串没有意义的代码，所以最后考虑使用截取的方式

**Comment by shenbh** [comment]
> 
> 
> 您好, 我也遇到了这个问题, 我的解决方案是:
> 
> ```js
> var gitalk  = new Gitalk({
>          // 在这里设置一下截取前50个字符串, 这是因为 github 对 label 的长度有了要求, 如果超过
>          // 50个字符串则会报错.
>         id: (location.pathname).split("/").pop().substring(0, 49),
>         distractionFreeMode: true,
>         language: language
>  });
> ```
> 
> 设置了之后, 无论名字长度为多少, 都可以保证创建成功.
> 
> 我的博客示例: view-source:http://blog.dengqinghua.net/badge_system.html 1081行

请问这段代码要贴到哪个文件下？
