### ISSUE TITLE
custom redirect_uri

### ISSUE THREAD

**Issue by upupming** [gitalk/gitalk#125]
I want to use a custom redirect uri:
```js
redirect_uri: location.origin + location.path + "#gitalk-container"
```

So that page is still at gitalk component after redirected from github.

Is it possible?

**Comment by booxood** [comment]
It can be done. See [here](https://github.com/gitalk/gitalk/blob/master/src/gitalk.jsx#L83).

**Comment by upupming** [comment]
I'm sorry to say that I cannot understand it.

I just saw [this line](https://github.com/gitalk/gitalk/blob/master/src/gitalk.jsx#L154), so I want to modify it to:
```js
      // Set the hash property
      location.hash = "gitalk-container";
      var query = {
        client_id: clientID,
        redirect_uri: location.href,
        scope: 'public_repo'
      };
```
Am I making the correct change?

**Comment by booxood** [comment]
Try it.

**Comment by TOMsworkspace** [comment]
‘’‘’
