### ISSUE TITLE
hexo部署到阿里云服务器上面，gitalk是否可以使用

### ISSUE THREAD

**Issue by jiang95** [gitalk/gitalk#127]
hexo部署到阿里云服务器上面，gitalk是否可以使用？我把我的hexo部署到了阿里云，好像gitalk不能使用，请教下，这是什么问题？

**Comment by booxood** [comment]
> 不能使用

是什么情况？

**Comment by jiang95** [comment]
就是我今天把我的hexo部署到阿里云上卖弄了，登入就跳转到我GitHub page上面的网址了。

**Comment by booxood** [comment]
你部署到阿里云后，你访问的链接变了，需要将之前 Github 登录完成后的跳转设置也修改下

**Comment by jiang95** [comment]
o  谢了
