### ISSUE TITLE
请问一下已经有 owner 了， admin 属性表示 collaborators ，为啥 admin 还必须要有了？

### ISSUE THREAD

**Issue by ehlxr** [gitalk/gitalk#13]
请问一下已经有 owner 了， admin 属性表示 collaborators ，为啥 admin 还必须要有了？不能设置为选填项吗？

**Comment by booxood** [comment]
可以设为选填项，判断如果没有 admin 那就取 owner，或者默认 owner 就是 admin 之一，但是既然是两个配置项，还是让各司其职的好，便于理解。

**Comment by mamboer** [comment]
@ehlxr 
我补充下，Gitalk是支持个人或组织项目的，设计的时候考虑到owner不一定是个人账号，而admin应为个人账号，所以就分开配置啦。

**Comment by ehlxr** [comment]
@booxood @mamboer 首先感谢开发这么好的工具👍。

admin 的存在我理解是有意义的，但是我觉得没必要必填项吧！个人拙见

**Comment by booxood** [comment]
就像前面说的

> 可以设为选填项，判断如果没有 admin 那就取 owner，或者默认 owner 就是 admin 之一

如果不限定为 `必填项` 就要做这样的判断

虽然某些情况下是可以少配置一个配置项，但是就把配置的含义弄的复杂了，增加了理解的成本，而多填一个含义清晰的配置项的成本应该很低吧。

**Comment by ehlxr** [comment]
当我看到这样的描述时，第一感觉就是我必须需要一个 collaborator，而我的 repo 就是我个人在维护的时候有点儿歧义
> **Required**. Github repository collaborators. (Ensure having write access to this repository)

**Comment by mamboer** [comment]
理解你的意思，我们想办法优化下
