### ISSUE TITLE
Related Issues not found

### ISSUE THREAD

**Issue by xuepro** [gitalk/gitalk#130]
Related Issues not found
Please contact @xx to initialize the comment
Login with Github

**Comment by booxood** [comment]
配置的 `XX` 是什么？

**Comment by XX** [comment]
Hmm...

**Comment by booxood** [comment]
@xuepro gitalk 与 gitment 的对利用 github issue 的实现原理是一样的，基本上是可以相互替换的，如果 gitment 可以 gitalk 应该也是可以的。
