### ISSUE TITLE
自定义 id 与 labels , 其实是很疑惑的

### ISSUE THREAD

**Issue by chinanf-boy** [gitalk/gitalk#132]
[readme.md 设置](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#%E8%AE%BE%E7%BD%AE) 上面说

- `id` String

```
Default: location.href.
页面的唯一标识。长度必须小于50。
```

而我带着一个问题 `我怎么跳到其他Issue单元` , 去实践步骤

> 比如这个带 `docs`的标签 Issue #5 

---

### 我的步骤

1. `git clone gitalk.github.io`
2. `start server`
3. `Edit` [index.html 137](https://github.com/gitalk/gitalk.github.io/blob/master/index.html#L137)

``` js
// 137
        id: 'Demo', // 在我看来, 这就是插件内部的缓存标签
```

#### to

``` js
       id: 'Demo',
       labels: ['docs'] // 默认 ['Gitalk']
```

站在我的角度, 应该是没有问题的但是❌

---

### 问题后

乱找一通后发现
[source src/gitalk.jsx](https://sourcegraph.com/github.com/gitalk/gitalk@master/-/blob/src/gitalk.jsx#L193)
``` js
 labels: labels.concat(id).join(','),
```

> `id` 也是 labels 之 一 `???`

也许站在`管理者admin的角度来说, who care`, 反正 只要 [createIssue](https://sourcegraph.com/github.com/gitalk/gitalk@master/-/blob/src/gitalk.jsx#L214) 初始化 , 自然而然带着 `id`开标签Issue

> 但我不认为, 这对 `id` 选项的解释对新手是好事

---

## 建议 加上 对 `id` 是`隐形标签`的解释, 在 `readme.md` 上

---

### 问题解决

``` js
       id: '', // 去掉 隐形标签 ✅
       labels: ['docs'] // 默认 ['Gitalk']
```

**Comment by booxood** [comment]
隐形标签是什么意思？ 

id 也是一个普通的标签。// 你是希望在 readme 上加这个说明吗？

**Comment by chinanf-boy** [comment]
嗯

**Comment by booxood** [comment]
增加一个说明也行

只是到目前为止，还很少有对这个地方有疑问的

**Comment by chinanf-boy** [comment]
是疑惑性

- id String

Default: location.href.
页面的唯一标识。长度必须小于50。Issue 标签之一
