### ISSUE TITLE
点赞的功能无法使用

### ISSUE THREAD

**Issue by ricosmall** [gitalk/gitalk#134]
报404错误了

![image](https://user-images.githubusercontent.com/18362949/39391171-f4e37646-4ad1-11e8-83bd-ea071747f900.png)

![image](https://user-images.githubusercontent.com/18362949/39391179-0816b6ce-4ad2-11e8-9178-0fba8d48831d.png)

**Comment by booxood** [comment]
在这个页面上是无法点赞的。。。很奇怪。。。（只能怀疑是因为评论太多了。。。Github 接口的 bug

可以找一个其他的地方再试一下点赞
