### ISSUE TITLE
Error: Validation Failed. 

### ISSUE THREAD

**Issue by fuzhouxxdong** [gitalk/gitalk#135]
![tim 20180428145550](https://user-images.githubusercontent.com/5198378/39393145-5ce7be60-4af4-11e8-8f96-61dffe4022d1.png)
what? 这是几个意思？

**Comment by booxood** [comment]
看下是不是  #102 这里讨论的问题。

**Comment by fuzhouxxdong** [comment]
是这个问题

**Comment by xuepro** [comment]
按照#106做的，评论显示不出来
