### ISSUE TITLE
gitalk评论区域不显示？

### ISSUE THREAD

**Issue by xuepro** [gitalk/gitalk#136]
帮我看看为什么评论显示不出来呢？about可以，其他文章后面没有评论，但我在post.html中已经按照网上说明做了，还是不行啊，谢谢！xuepro.github.io

**Comment by xuepro** [comment]
将md5（location.pathname）换成一个字符串如'hello'就出现评论了。什么原因？这个id到底应该怎么设置呢？

**Comment by booxood** [comment]
现在已经可以了？

**Comment by yujianbin** [comment]
“未找到相关的 Issues 进行评论

请联系 @xxx 初始化创建”


提示这个改如何解决呢

**Comment by keveon** [comment]
我也碰到了类似的问题,我是在 `docsify` 里边用的, 把 `id` 设置成了 `window.location.hash`, 这么搞会有一个问题, 如果是单页应用没问题, 但是多页的话就不行了, 只有第一次打开的那个页会有评论, 切换其他页之后还是显示的第一个页面的评论, 需要刷新整个页面才行.

---

还没想好要怎么搞, 是不是有 `地址栏变更后 gitalk 自动重绘` 的机制就好了?

**Comment by keveon** [comment]
@yujianbin 你那个问题用 xxx 的 github 账号登陆一下就好了。

**Comment by yuyongsheng1990** [comment]
conclusion:(1) 勾选github-setting总的issue。(2) github.io博客地址为https://，并与gitalk中urls地址保持一致。

**Comment by xcatliu** [comment]
@keveon 我找到一个办法了 https://github.com/gitalk/gitalk/issues/388

**Comment by walkingtyphoon** [comment]
为什么我的评论内容不显示，而且有的文字还会重复 这是我的站点www.isforyou.org.cn
