### ISSUE TITLE
https://api.github.com/user 401 (Unauthorized)

### ISSUE THREAD

**Issue by ElderJames** [gitalk/gitalk#138]
401报错了

**Comment by Kevinl7** [comment]
解决了么？  我也是这个错误。。。

**Comment by Kevinl7** [comment]
## 已解决， 用户名搞错， 
# 要填github用户名 
# 不要填登录名
用户名如图
![image](https://user-images.githubusercontent.com/22197685/39859524-b71a9962-546c-11e8-9f47-d308cef9207c.png)

**Comment by ElderJames** [comment]
我就是填的用户名~真可以？

**Comment by ElderJames** [comment]
确认了，是一开始没点击授权报错，应该要判断是否有token再请求

**Comment by ruanwenjun** [comment]
怎么解决

**Comment by yanbinghu** [comment]
### 遇到了同样的问题，但是造成的原因不一样
### 原因：之前的github pages一直是http方式访问，最近修改为强制https访问，之后就导致gitalk初始化，或者登录的时候出现401错误
### 解决：修改comment的app callback url为https地址，或者将github pages的强制https访问去掉。
![image](https://user-images.githubusercontent.com/23411939/45131378-56ec5980-b1bf-11e8-90ff-f4db0186db62.png)

**Comment by cqliulei** [comment]
> 401报错了



> 确认了，是一开始没点击授权报错，应该要判断是否有token再请求

我现在也是一直报401错误，没发现问题出在哪儿呢

**Comment by custertian** [comment]
我是在添加了 `  id: location.pathname,` 这个字段就可以了

**Comment by afan0228** [comment]
怎么解决到底，目前的方法都不能解决
