### ISSUE TITLE
“评论”按钮和“使用GitHub登录”按钮在chrome 和 Firefox 下 点击没反应

### ISSUE THREAD

**Issue by hoxis** [gitalk/gitalk#139]
“评论”和“使用GitHub登录”按钮 chrome（65.0.3325.181） 和 Firefox（59.0.3）下 点击没反应，在 opera 和 IE 下可以。不清楚是不是配置有问题啊。

[https://hoxis.github.io/ansible-modules.html](https://hoxis.github.io/ansible-modules.html)

**Comment by booxood** [comment]
我用 chrome（66.0.3359.139） 试了下，是会跳转到 GitHub 登录认证页面的啊

**Comment by hoxis** [comment]
搞定了，是油猴子的一个[脚本](https://cat7373.github.io/remove-web-limits/)搞的鬼，停用后就正常了
