### ISSUE TITLE
关于、标签、分类页面也会出现gitalk评论框（归档没有出现）？

### ISSUE THREAD

**Issue by ithou** [gitalk/gitalk#148]
不想在 **关于**、**分类**和**标签** 页面看到gitalk评论框怎么办？

**Comment by nameNotNull** [comment]
你解决了这个问题吗

**Comment by ithou** [comment]
已解决。
在 `hexo/source` 下分别新建 `about`、`categories`、`tags` **文件夹**，每个文件夹里面都新建一个 `index.md` 文件，内容为：

```
---
title:  # 标题
type: "about"  # about、categories、tags
comments: false
---

```

**Comment by nameNotNull** [comment]
太好了，感谢感谢，之前在哪看到过，哈哈
