### ISSUE TITLE
能否提供一些事件对象接口？

### ISSUE THREAD

**Issue by Chickking** [gitalk/gitalk#149]
譬如，当评论加载完成时、新增评论时、发表评论时，提供事件对象接口来方便执行其它动作？

有了这些接口，我就能够优雅地在评论加载完成后进行数学公式的解析。

**Comment by booxood** [comment]
增加了一个配置 updateCountCallback，可以获取到总数。

**Comment by jerryc127** [comment]
@booxood  你好
這個updateCountCallback如何使用？
