### ISSUE TITLE
请问如何完全(永久)取消某个 issue 订阅

### ISSUE THREAD

**Issue by drakeet** [gitalk/gitalk#15]
我在 demo 中回复了一条评论，导致之后一旦有人新增评论，我就会收到邮件提醒，我想原因是评论后就会默认订阅这个 issue，即使别人不是回复你，也会收到提醒。

于是我进入到 demo 相关的具体 issue，点击了 **unsubscribe**，取消订阅，可是后续有人评论，仍然给我发提醒邮件了，而且我的账号再次被置为订阅了该 issue，对此十分困扰，不知如何才能完全取消评论订阅。

![image](https://user-images.githubusercontent.com/5214214/29114855-2126881a-7d28-11e7-8d92-a55bb83079d3.png)

**Comment by mamboer** [comment]
原因是有人在issue里主动@了你，这个是GitHub的交互，我明天幫你看看有沒有辦法

**Comment by drakeet** [comment]
谢谢，但看起来没有人 @ 我

**Comment by booxood** [comment]
![image](https://user-images.githubusercontent.com/2151410/29123860-afb6d924-7d49-11e7-913b-270bf0aed101.png)

**Comment by mamboer** [comment]
@drakeet 你试试到 https://github.com/notifications 页面，取消关注试试，
不一定管用，当有别的童鞋@你的时候估计还是会有收到提醒的。
实在觉得烦，可取消关注整个gitalk项目（star还是可以留着的😄）。
试试吧

![image](https://user-images.githubusercontent.com/85879/29125380-317f0d74-7d4e-11e7-8fb5-70c024979b88.png)

**Comment by drakeet** [comment]
并没有效果，仍然不断收到邮件，我想只能创建邮件过滤来拦截提醒了👻

**Comment by drakeet** [comment]
看起来似乎只要不被人 at，就不会重新“被订阅”，所以这个 issue 可以暂时性解决和关闭。不过我仍然觉得使用 GitHub issue 来作为评论系统不太合适，因为会给评论者无意中带来困扰。一旦评论，就会默认收到文章的后续全部提醒邮件，而且跑到 GitHub 取消了之后，如果有人 at 你，还会再次被订阅上。
虽然这个项目 UI 做得很漂亮精致。: )

**Comment by iNiL0119** [comment]
现在这个问题解决了吗

**Comment by booxood** [comment]
@iNiL0119 没有，GitHub 的 issue 提醒机制就是这样的，GitHub 调整了才行。

**Comment by gclxxmqq** [comment]
![image](https://user-images.githubusercontent.com/31238796/55208662-f5064680-5219-11e9-8be3-730dcb3052c1.png)
setting

**Comment by i-cooltea** [comment]
![image](https://user-images.githubusercontent.com/20251640/62669523-789f2380-b9c2-11e9-8068-435c46cd5ac1.png)

**Comment by super-he** [comment]
谢谢，我也碰到这个问题。。赶紧去网站公告下哈哈

**Comment by toanoyx** [comment]
想问问这个问题解决了吗？

**Comment by toanoyx** [comment]
有什么可以不被通知的方法吗？

**Comment by super-he** [comment]
抱歉哈，你可以取消订阅这个仓库，具体见我破站的留言板块下有说明


 
---原始邮件---
发件人: "toanoyx"<notifications@github.com&gt;
发送时间: 2020年7月20日(星期一) 下午4:21
收件人: "gitalk/gitalk"<gitalk@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"richardhe"<super_he@foxmail.com&gt;;
主题: Re: [gitalk/gitalk] 请问如何完全(永久)取消某个 issue 订阅 (#15)




 
有什么可以不被通知的方法吗？
