### ISSUE TITLE
Bug？暴露 Client_id和Client_secret ？

### ISSUE THREAD

**Issue by ithou** [gitalk/gitalk#150]
配置gitalk时，在主题配置 `_config.yml` 文件中有这样部分代码：
``` C
gitalk:
    enable: true
    github_user: xx
    github_repo: xx
    admin: xx
    client_id: asdnaslkndassad7sd8s7ds6d  ##我随便编的
    client_secret: 32alu9sds9sd094e7044a3e55   ##我随便编的
```
如果这样写好，直接 `hexo g -d` 的话，不就在**历史提交记录commits**里向外暴露了Client_id和Client_secret吗？

**Comment by booxood** [comment]
参考这里：[is-it-safe-to-make-my-client-secret-public ](https://github.com/imsun/gitment#is-it-safe-to-make-my-client-secret-public)

**Comment by wsdjeg** [comment]
但是实际上，你给的连接并未解释清楚是否可以暴露secret

**Comment by wsdjeg** [comment]
感谢，明白了。
