### ISSUE TITLE
The windows will shack when typing in the gitalk （窗口打字时抖动）

### ISSUE THREAD

**Issue by hechangran** [gitalk/gitalk#152]
When typing in the ‘leave a comment’ box, the entire screen will shack. It is not a big deal but please fix it. Thanks. My broswer is Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by booxood** [comment]
版本 67.0.3396.87（正式版本） （64 位）

It's not happen. Is it something else?

**Comment by hechangran** [comment]
Please refer to this video
https://youtu.be/UBG5sb5XRPg
Many thanks!

**Comment by booxood** [comment]
Is it because the scroll bar?

**Comment by hechangran** [comment]
I don't think so. I only type and didn't use the scroll bar.

**Comment by booxood** [comment]
Input event trigger something, cause frequent display or hiding ...

**Comment by hechangran** [comment]
Thank you. I resolved the problem. It is caused by the Chrome plugin 'Grammarly'. If I disable the plugin, then the shacking of the screen disappears.
