### ISSUE TITLE
hexo yilia 主题配置 gitalk 评论后无法初始化创建 issue

### ISSUE THREAD

**Issue by tmgycsz** [gitalk/gitalk#153]
看了好多全是next主题下的初始化问题，而我是在yilia这个真不清楚是什么问题。
首次登录授权后面返回的映射页面就是下图

![1](https://user-images.githubusercontent.com/25758866/41712240-afe29ed4-757c-11e8-8191-465e2ab0f967.png)

1.这是post下的gittalk文件
![2](https://user-images.githubusercontent.com/25758866/41712343-ed88a404-757c-11e8-8f20-589463f1bea7.png)

2.这是_config.yml配置
![4](https://user-images.githubusercontent.com/25758866/41712510-468cec4a-757d-11e8-8cf1-3b67cb2edebf.png)

3.这是判断是否加载的条件
![3](https://user-images.githubusercontent.com/25758866/41712464-2dd21946-757d-11e8-9392-f4020ad5493f.png)

**Comment by tmgycsz** [comment]
搞了半天发现是不能再博客名中加（）也是醉了

**Comment by booxood** [comment]
没问题就先关闭了
