### ISSUE TITLE
关于1.3版本移动端样式

### ISSUE THREAD

**Issue by FeDemo** [gitalk/gitalk#154]
## 目前移动端是这样的
![](https://imgsa.baidu.com/forum/w%3D580/sign=835c4cfa97504fc2a25fb00dd5dce7f0/779b077b02087bf4a6a3971bfed3572c10dfcf80.jpg)
## 可以的话  把 `margin-left: 1.25em;` 这个css属性去了会好看点
![](https://imgsa.baidu.com/forum/w%3D580/sign=2ede860d37c79f3d8fe1e4388aa3cdbc/50fd3787e950352a21bfe6fa5f43fbf2b3118b71.jpg)

**Comment by wonpn** [comment]
+1，移动端的适配确实有错位，另外两个按钮挤的太近了
