### ISSUE TITLE
作者大大可否开放未压缩的cdn文件源码

### ISSUE THREAD

**Issue by pkwenda** [gitalk/gitalk#158]
我打算创建一个程序员的论坛进行开源，我有需求，非`admin`用户进行自由发言创建`isuess`，我下载了您的`https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js`源码手动更改了源码，实现了此功能，但还想实现一些其他的功能，压缩后的代码阅读难度太大，可否提供一个未压缩的`gitalk.js`发给我，蟹蟹0.0

如果方便的话我的邮箱 `sis.nonacosa@gmail.com`

![image](https://user-images.githubusercontent.com/14212375/42136587-fa944f42-7d90-11e8-9615-b1a6614710ef.png)

**Comment by booxood** [comment]
在这个 repo 里的 dist/ 目录下有。

修改功能建议你看 src 里的代码，修改后，运行 npm run build 得到合并打包后的代码。

**Comment by pkwenda** [comment]
@booxood 好的，感谢，我先用目前的 `gitalk`，等 实现玩网站功能 `fork` 改下，因为可能需要一些回调。蟹蟹
