### ISSUE TITLE
Error: Not Found.

### ISSUE THREAD

**Issue by iloveyz** [gitalk/gitalk#16]
如题，而且点击登陆也登陆不了，直接刷新页面，不知道怎么解决，有知道的可以帮忙解决一下吗。谢谢！~

**Comment by booxood** [comment]
`Error: Not Found.` 是指找不到对应的 repo

你配置的 repo 和 owner 是什么？

是不是与 #4 一样的问题

**Comment by mamboer** [comment]
@booxood 看来要在Readme，加一个常见问题QA

**Comment by iloveyz** [comment]
@booxood 
repo: https://github.com/iloveyz/iloveyz.github.io
owner: iloveyz
admin: iloveyz
我是这样写的

**Comment by booxood** [comment]
repo 改为 `iloveyz.github.io`

**Comment by booxood** [comment]
@mamboer 有 issue 记录着

**Comment by iloveyz** [comment]
@booxood 我也试了会提示我说需要初始。不知道怎么回事

**Comment by booxood** [comment]
@iloveyz 那点击初始化

**Comment by iloveyz** [comment]
@booxood 

未找到相关的 Issues 进行评论
请联系 @iloveyz 初始化创建
使用 Github 登录

应该怎么初始创建呢？

**Comment by booxood** [comment]
@iloveyz  Github OAuth 没有成功，检查下
-  `clientID` 和  `clientSecret` 是否正确
- 申请的 Github Application 的 `Authorization callback URL` 是否正确

**Comment by booxood** [comment]
@iloveyz  噢！可能是跟 gitment 冲突了，因为都会去获取 url 上查询参数 code 然后再去掉！

**Comment by iloveyz** [comment]
@booxood 
Github OAuth 应该没写错，是啊，以前用的gitment，怎么解决冲突呢。万分感谢，这么晚还解答我的问题。

**Comment by booxood** [comment]
@iloveyz 不引入 gitment 的 js 试试

**Comment by iloveyz** [comment]
@booxood 
不引入也不行，还是`未找到相关的 Issues 进行评论`

**Comment by booxood** [comment]
@iloveyz 
你有登录吗？

**Comment by iloveyz** [comment]
@booxood 
点击登录登录不了

**Comment by booxood** [comment]
@iloveyz 
我在你的 blog 上都可以正常登录啊

**Comment by iloveyz** [comment]
@booxood 
我登陆就只是刷新页面（）
地址栏一闪而过https://iloveyz.github.io/2017/08/07/hello-world/?code=6782b991dd3f254eac59

**Comment by iloveyz** [comment]
@booxood 如果说登陆状态，我一直是保持登录的，然而还是提示使用github登陆点击那个按钮就向我如上所说

**Comment by booxood** [comment]
@iloveyz 

![image](https://user-images.githubusercontent.com/2151410/29153006-7296fc76-7dbd-11e7-8acd-520c32c10ce2.png)
你登录后，有 `GT_ACCESS_TOKEN` 吗

**Comment by iloveyz** [comment]
@booxood 
没有
![1.png](https://i.loli.net/2017/08/10/598bd1a85f438.png)

**Comment by booxood** [comment]
@iloveyz 
![image](https://user-images.githubusercontent.com/2151410/29155158-9250833e-7dcc-11e7-8241-8e0ce1b9f855.png)

还是有加载 gitment.js 啊？

**Comment by iloveyz** [comment]
@booxood 
好了，您说的对，的确是和gitment.js冲突所导致的无法使用。。。

**Comment by iloveyz** [comment]
@booxood 
我又来了，- -，不知怎滴，我把issues全部close后又不能用了。。。又提示让我初始了。这次可以登录但登录后还是要我初始。。。

**Comment by booxood** [comment]
评论对应的 issue 不能 close

**Comment by iloveyz** [comment]
@booxood 可以告知怎么初始吗？

**Comment by iloveyz** [comment]
@booxood 谢谢哈，我多点了几下用github登录就好了，- -。嘿嘿！~

**Comment by octowhale** [comment]
如果出现 `Not Found` 可能因为把  `repo` 的值写成 `OAuth App` 的名称了。

**Comment by xuepro** [comment]
我也是一样的问题，不行啊！

**Comment by konwworld** [comment]
https://api.github.com/user  
401 Unauthorized

**Comment by konwworld** [comment]
Error: Not Found
https://api.github.com/repos/konwworld/myblog-comments/issues?client_id=1f02192554bde9b07bf8&client_secret=615f451a41a0d0fa09621599ade06a7ab21b5587&labels=gitment,%2Flife&t=1544086926422

404错误，怎么解决啊

**Comment by atlasnq** [comment]
> Error: Not Found
> https://api.github.com/repos/konwworld/myblog-comments/issues?client_id=1f02192554bde9b07bf8&client_secret=615f451a41a0d0fa09621599ade06a7ab21b5587&labels=gitment,%2Flife&t=1544086926422
> 
> 404错误，怎么解决啊

尴尬，我登陆后也是404

**Comment by Hughshine** [comment]
如果博仓库客是私有的，需要为gitalk开新仓库。
