### ISSUE TITLE
Error: Cannot read property 'avatarUrl' of null

### ISSUE THREAD

**Issue by amorist** [gitalk/gitalk#160]
```
gitalk.jsx:131 err: TypeError: Cannot read property 'avatarUrl' of null
    at getComments.js:93
    at Array.map (<anonymous>)
    at getComments.js:89
```
![sl8pjj fjcbgmoe0i49xry2](https://user-images.githubusercontent.com/14037268/42212579-16b2a3be-7ee9-11e8-90ea-e98eaa7b6d13.png)

**Comment by booxood** [comment]
有个评论的 author 是 null。。 难道是该用户注销了？

**Comment by amorist** [comment]
估计是

**Comment by yanbinghu** [comment]
![image](https://user-images.githubusercontent.com/23411939/45006035-80737c80-b029-11e8-9861-3394c3643d9b.png)

用户被删除了，只需要把这个用户评论的内容删除就可以恢复了，不过这貌似也不是最终解决办法啊，还需要gitalk本身做一些保护处理。

**Comment by CoderMing** [comment]
我试着注销一个user 然后发现并不会报错。因为GitHub自动将delete的user的信息转成ghost了：
![image](https://user-images.githubusercontent.com/25007676/45143268-61bde300-b1ed-11e8-8c3f-bec8a6edd16e.png)
楼主的bug应该不是注销user导致的。

**Comment by CoderMing** [comment]
@yanbinghu 不会。其他信息都存在（都会变成“ghost”这个账户的信息）。
