### ISSUE TITLE
可否支持直接用id来固定issues

### ISSUE THREAD

**Issue by ydq** [gitalk/gitalk#167]
现在是使用**labels**来确定当前评论的issues的，目前有个博客项目是直接使用issues来写博客，然后直接用github的api来读取issues显示的，这样的话其实每个issues已经存在一个id了，所以希望直接支持用id来确定评论的issues，而不是必须要设置labels。

**Comment by ydq** [comment]
例子：https://github.com/ydq/blog/issues/8  对应  https://darren.work/post/8

因为本身也是用issues来写博客的，所以使用gitalk评论刚好也可以在下面，但是现在是每篇文章必须手打个唯一标签（目前是#+当前ID，毕竟id肯定是唯一的），所以希望gitalk 支持直接使用id而不是必须要labels。

**Comment by ydq** [comment]
我觉得可以增加一个id属性，然后直接根据id属性去读取，如果没有对应id的issues，则再将#id值作为label去做查询这样子🙂

**Comment by booxood** [comment]
@ydq 这个 [PR#168](https://github.com/gitalk/gitalk/pull/168) 是不是你想要的？

**Comment by ydq** [comment]
@booxood 对对对~ 哈哈原来有了呀  谢谢~
