### ISSUE TITLE
gitalk没有自动升级

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [gitalk/gitalk#169]
如题，我理解的是会自动升级到1.3.3的，但是目前我的博客gitalk版本还是1.2.2

**Comment by booxood** [comment]
你是通过外链的方式引入吗？这跟引入的链接有关。如果指定了详细的版本（例如：1.2.2）是不会自动引入新版本的。

希望可以自动引入最新的版本，可以采用 README 里提供的方式。

**Comment by booxood** [comment]
没有其他问题，先关闭了。
