### ISSUE TITLE
项目部署服务为https时，github授权登录时异常

### ISSUE THREAD

**Issue by zhangbiy** [gitalk/gitalk#175]
<img width="484" alt="wx20180823-121346 2x" src="https://user-images.githubusercontent.com/24889151/44504337-fee92980-a6cd-11e8-85de-d3c827ca528c.png">
github登录授权，一个为https,授权为http出现异常。

**Comment by booxood** [comment]
噢 你的浏览器是什么版本呀

**Comment by zhangbiy** [comment]
已经解决了，改了一下js里跳转的地址，改成https的，后来就可以正常使用了
