### ISSUE TITLE
总是无法创建评论框

### ISSUE THREAD

**Issue by smallnest** [gitalk/gitalk#176]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/865763/44659194-ef534300-aa35-11e8-9f79-c0ed2475cb9c.png">

相关的issue也没有在github上创建出来，web控制台没看到什么错误。

例子： https://colobu.com/2018/08/27/learn-go-module/

貌似在我将网站升级为https后出现了这个问题。

**Comment by smallnest** [comment]
这个issue是我手工创建的。因为通过按钮创建不了，所以我手工实验了一下

**Comment by CoderMing** [comment]
issue默认是根据label定位的，不带对应的label就定位不到，你可以用管理员账户手动创建一个新issue

**Comment by smallnest** [comment]
解决了， 需要更新一下  OAuth 程序，将里面的回调地址环换成https的
