### ISSUE TITLE
关于区块引用嵌套代码块的显示问题

### ISSUE THREAD

**Issue by tianma8023** [gitalk/gitalk#178]
比如说：
> I'm a block. 我是区块
> ```
> // I'm a code block. 我是代码块 
> print("hello world")
> ```
但是在 `1.4.0` 的 gittalk中会这样显示：
 
![1536030084 1](https://user-images.githubusercontent.com/7833704/45008152-9be38500-b033-11e8-8cf1-ae09eaa0b172.jpg)

![1536030682 1](https://user-images.githubusercontent.com/7833704/45008098-59ba4380-b033-11e8-9142-efc0a1c3a953.jpg)

页面链接可以点 [这里](http://tianma.space/post/3998746934#gitalk-comment)

代码块中的字体被放大~

**Comment by CoderMing** [comment]
我查看了下你页面的样式，发现blockquote有下面的样式：
![image](https://user-images.githubusercontent.com/25007676/45137187-2f56ba80-b1da-11e8-9e4b-04c7ae24d75a.png)
这个样式不是gitalk自带的。而对于引用（即Markdown中的 '>'），渲染器会渲染成blockquote。而你的页面对blockquote的文字大小有设置，就导致了文字偏大。
建议处理方式是自定义一下样式，把blockquote的字体大小设置成'100%'

**Comment by tianma8023** [comment]
@CoderMing 十分感谢，是我自己疏忽了~~ 🌅
