### ISSUE TITLE
没登录用户的时候似乎有一个很久很久的加载啊？

### ISSUE THREAD

**Issue by inkss** [gitalk/gitalk#179]
如下图，有什么方法能避免吗？

![image](https://user-images.githubusercontent.com/31947043/45365340-e5713880-b60e-11e8-8b9d-9c9e4c83c36d.png)

这张图是登录后的网络加载情况：
![image](https://user-images.githubusercontent.com/31947043/45365467-29643d80-b60f-11e8-94d0-f2fef4537d5f.png)

**Comment by booxood** [comment]
没办法，可能第一次请求 Github 的接口比较慢
