### ISSUE TITLE
评论的滚动条能取消么

### ISSUE THREAD

**Issue by justde** [gitalk/gitalk#181]
我看到其他人的评论区很少有这个滚动条
请问我的评论区滚动条能取消么
[请评论看下效果](https://justd.xyz/2017/04/18/new-theme-h2o.html)

谢谢

**Comment by CoderMing** [comment]
我在你的页面没有看到有异常。如果的确有问题，请发下浏览器版本，贴一下截图吧😊

**Comment by justde** [comment]
谢谢你，
完成这个问题的原因是模版样式限制了评论模块，现在已经解决了。

张敬东

在 2018年9月13日，20:07，CoderMing <notifications@github.com<mailto:notifications@github.com>> 写道：


我在你的页面没有看到有异常。如果的确有问题，请发下浏览器版本，贴一下截图吧😊

**Comment by booxood** [comment]
已经解决了那我关闭 issue 啦
