### ISSUE TITLE
关于gitalk新建一个repo专门用来托管issue的问题

### ISSUE THREAD

**Issue by oukohou** [gitalk/gitalk#186]
我看到一个在[关于gitalk最小化权限的issue](https://github.com/gitalk/gitalk/issues/95)中的回答是新建一个账号的repo来托管，我也这么做了，想请问ekyll中gitalk的具体配置具体是怎么样的呢？
![image](https://user-images.githubusercontent.com/16237619/46255303-ec80bd80-c4cd-11e8-94e5-e0fc3955eaf7.png)

我的会显示error：
![image](https://user-images.githubusercontent.com/16237619/46255306-f30f3500-c4cd-11e8-96e2-481604d1780b.png)

我的具体配置是：
![image](https://user-images.githubusercontent.com/16237619/46255308-fa364300-c4cd-11e8-9e94-bfc94c47a4b6.png)

其中的信息，在admin以上都是github小号的配置信息，admin是我的大号的github账号。
也尝试过了吧admin中的账号改成小号，依然是同样地错误。
请问是否哪里配置错了呢？
谢谢！
致礼！
预祝国庆愉快！

**Comment by booxood** [comment]
新建的 repo 有把你的 `大号` 添加为 `Collaborators` 吗？

**Comment by oukohou** [comment]
> 新建的 repo 有把你的 `大号` 添加为 `Collaborators` 吗？

没有，我试试

**Comment by islwei** [comment]
repo 应该写 username.github.io吧

**Comment by oukohou** [comment]
> repo 应该写 issue-support.github.io吧
> 而且应该 admin: ['kohou-wang']
> 
> * `[^]`  给你贴个例子吧
> 
> ```lisp
> clientID: '3654916*****0c0038c28',
> clientSecret: 'd90d031a*****0e0fa4c7fe2fae747b96b',
> repo: 'Strange-AI.github.io',
> owner: 'Strange-AI',
> admin: ['jinfagang', 'Strange-AI'],
> ```
> 
> 而且你的clientID感觉不太对劲

新建了repo： issue-support.github.io，
现在的配置如下：
![image](https://user-images.githubusercontent.com/16237619/46589820-c9af6400-cae0-11e8-99c7-308c3bf07155.png)
这些配置全是小号的，然后出现的错误是：
![image](https://user-images.githubusercontent.com/16237619/46589834-e350ab80-cae0-11e8-8818-db6d4fd731da.png)
查看了一下issue请求的参数如下：
![image](https://user-images.githubusercontent.com/16237619/46589849-febbb680-cae0-11e8-8a2e-bd04eb3c65f7.png)
请问错误是在？
谢谢！

**Comment by islwei** [comment]
> > repo 应该写 issue-support.github.io吧
> > 而且应该 admin: ['kohou-wang']
> > 
> > * `[^]`  给你贴个例子吧
> > 
> > ```lisp
> > clientID: '3654916*****0c0038c28',
> > clientSecret: 'd90d031a*****0e0fa4c7fe2fae747b96b',
> > repo: 'Strange-AI.github.io',
> > owner: 'Strange-AI',
> > admin: ['jinfagang', 'Strange-AI'],
> > ```
> > 
> > 
> > 而且你的clientID感觉不太对劲
> 
> 新建了repo： issue-support.github.io，
> 现在的配置如下：
> ![image](https://user-images.githubusercontent.com/16237619/46589820-c9af6400-cae0-11e8-99c7-308c3bf07155.png)
> 这些配置全是小号的，然后出现的错误是：
> ![image](https://user-images.githubusercontent.com/16237619/46589834-e350ab80-cae0-11e8-8818-db6d4fd731da.png)
> 查看了一下issue请求的参数如下：
> ![image](https://user-images.githubusercontent.com/16237619/46589849-febbb680-cae0-11e8-8a2e-bd04eb3c65f7.png)
> 请问错误是在？
> 谢谢！

好吧 第一次见这种格式的clientId 
配置里的admin 是 Array
改成admin:['kohou-wang']试试

**Comment by islwei** [comment]
@oukohou
抱歉，今天有些忙
尝试把owner改成kohouwang试试
因为我看你小号的github name是这个

**Comment by oukohou** [comment]
@islwei 谢谢你的回复，这个是我昨天下午才改的，之前是kohou-wang，因为怕是因为中间的横线引起的问题，所以改了一下，配置里的信息都是跟这个同步的，所以不存在这个问题～～还是谢谢你的回复。

**Comment by Henton** [comment]
你好，问题还存在吗？存在的话admin改成admin: ["'kohou-wang'"]试一下呢

**Comment by oukohou** [comment]
> 你好，问题还存在吗？存在的话admin改成admin: ["'kohou-wang'"]试一下呢

额，谢谢你的回复。我已经换到了Valine，没有精力来折腾了～～

**Comment by booxood** [comment]
用小号新建一个 repo，然后把自己加到这个 repo 的贡献者里，然后把小号和自己的用户名都配置到 admin 里，保证都可以创建 issue。

**Comment by booxood** [comment]
先关闭，有反馈再打开。
