### ISSUE TITLE
IE 11下头像图标出现错位、放大。

### ISSUE THREAD

**Issue by wonpn** [gitalk/gitalk#187]
如图：
![](https://ws1.sinaimg.cn/large/82054d13ly1fvt2n4toehj20p30di3yt.jpg)

看了下 https://gitalk.github.io/ 的页面也有同样的问题

**Comment by islwei** [comment]
看起来是未登录状态下的SVG有问题。。。等大神来给解决吧

**Comment by pmkol** [comment]
同问如何解决，我也遇到了

**Comment by pmkol** [comment]
今天抽空研究了一下，给出一种在IE11下临时的解决办法，还希望作者不忙的时候能够修复这个BUG
在JS代码下方添加：
<style>
.gt-ico-github{
width:52px!important;
height:52px!important;
}
</style>

**Comment by booxood** [comment]
@pmkol 我装个虚拟机试下

**Comment by booxood** [comment]
已修复，发布了 v1.4.1 。

**Comment by lolifamily** [comment]
问题又出现了啊！！！！！ @booxood
