### ISSUE TITLE
diaspora 主题出现 Error: Validation Failed.

### ISSUE THREAD

**Issue by xinpengfei520** [gitalk/gitalk#188]
Error: Validation Failed.

![image](https://user-images.githubusercontent.com/7455269/46568486-51c62a00-c978-11e8-922a-dc0ecd123310.png)

**Comment by booxood** [comment]
先看下是不是这个问题 [Q&A](https://github.com/gitalk/gitalk/wiki/Q&A#%E6%8A%A5%E9%94%99-error-validation-failed)

**Comment by xinpengfei520** [comment]
非常感谢，我看了一下确实是 label 过长的原因，短的没这个问题！
