### ISSUE TITLE
Error: Cannot read property 'repository' of null

### ISSUE THREAD

**Issue by dreamkong** [gitalk/gitalk#189]
`Error: Cannot read property 'repository' of null`
未登录GitHub账号的时候是可以看见评论的 登陆后就出现这个问题

**Comment by dreamkong** [comment]
已解决
原因是perPage 传成`string`类型 实际要求`int`类型

**Comment by dreamkong** [comment]
http://blog.dreamkong.cn

**Comment by LeeYiua** [comment]
你好博主，你这是怎么解决的呢？

**Comment by shlinym** [comment]
> 你好博主，你这是怎么解决的呢？

string to int

perPage: 15

```js
perPage: parseInt("<%=theme.gitalk.perPage%>"),
```
