### ISSUE TITLE
使用md5后，仍出现Error:Validation Failed.

### ISSUE THREAD

**Issue by sunshineYin** [gitalk/gitalk#191]
就是检查了配置文件，应该都没问题。看之前的issue好像是说repo设置的问题，但是我的设置应该是对的吧？而且，本地测试和在GitHub pages上都是not `found。。
gitalk:
  enable: true  # 是否开启 Gitalk 评论
  owner: sunshineyin   # GitHub 用户名     
  repo: sunshineyin.github.io        #仓库名称
  ClientID: xxxxxx
  ClientSecret: xxxxxx
  admin: sunshineyin   # GitHub 用户名
  distractionFreeMode: true
不太清楚到底是咋回事，先谢谢大家了！

**Comment by sunshineYin** [comment]
已经解决了，是没有对gitalk.swig文件做修改的缘故。即：
   <script type="text/javascript">
        var gitalk = new Gitalk({
          clientID: '{{ theme.gitalk.ClientID }}',
          clientSecret: '{{ theme.gitalk.ClientSecret }}',
          repo: '{{ theme.gitalk.repo }}',
          owner: '{{ theme.gitalk.githubID }}',
          admin: ['{{ theme.gitalk.adminUser }}'],
          id: location.pathname,
          distractionFreeMode: '{{ theme.gitalk.distractionFreeMode }}'
        })
        gitalk.render('gitalk-container')           
       </script>
没有对以上做修改。

**Comment by sunshineYin** [comment]
又有了新的问题，按照#102的方法，我安装了一个MD5的js文件（路径为：/js/src/md5.min.js），然后配置gitalk.swig文件如下：
{% if page.comments && theme.gitalk.enable %}
  <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">

  <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
  <script src="/js/src/md5.min.js"></script>
  
   <script type="text/javascript">
        var gitalk = new Gitalk({
          clientID: 'xxxxxxx',
          clientSecret: 'xxxxxxxxx',
          repo: 'sunshineyin.github.io',
          owner: 'sunshineyin',
          admin: ['sunshineyin'],
          id: md5(location.pathname),
          distractionFreeMode: 'true'
        })
        gitalk.render('gitalk-container')           
       </script>
{% endif %}

依旧有Error:Validation Failed的问题，谢过大家了！

**Comment by dudongpeng** [comment]
解决了吗， 我也有这个问题哦？同求解决办法

**Comment by HuangDayu** [comment]
> 又有了新的问题，按照#102的方法，我下载了一个MD5的js文件（路径为：/js/src/md5.min.js），然后配置gitalk.swig文件如下：
> 
> ```
> {% if page.comments && theme.gitalk.enable %}
>   <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
> 
>   <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
>   <script src="/js/src/md5.min.js"></script>
>   
>    <script type="text/javascript">
>         var gitalk = new Gitalk({
>           clientID: 'xxxxxxx',
>           clientSecret: 'xxxxxxxxx',
>           repo: 'sunshineyin.github.io',
>           owner: 'sunshineyin',
>           admin: ['sunshineyin'],
>           id: md5(location.pathname),
>           distractionFreeMode: 'true'
>         })
>         gitalk.render('gitalk-container')           
>        </script>
> {% endif %}
> ```
> 依旧有Error:Validation Failed的问题，谢过大家了！

https://cdn.bootcss.com/blueimp-md5/2.10.0/js/md5.js

**Comment by sunshineYin** [comment]
我发现过一段时间后，它就没有error了，自动就好了，我也不太清楚是咋回事。。

**Comment by booxood** [comment]
是不是因为缓存所以更新没有生效？

**Comment by sunshineYin** [comment]
我感觉可能是，我中间也没做任何操作，在更新了第二篇博文后就没问题了

**Comment by booxood** [comment]
@sunshineYin OK。没问题了那 issue 先关闭了。
