### ISSUE TITLE
re-render support

### ISSUE THREAD

**Issue by wongoo** [gitalk/gitalk#198]
After the first function call `render`,  I'd like to change the id of gitalk, and call render again, but it does not work. 

So, doest it support re-render? How ?

**Comment by wongoo** [comment]
I hacked it:

    window.$docsify = {
      plugins: [
        function(hook, vm) {
          hook.doneEach(function(){
            document.getElementById('gitalk-container').innerHTML = "";
            NewGitalk().render('gitalk-container');
          });
	     }	
      ]
    }
  
    function NewGitalk(){
      return new Gitalk({
        clientID: 'xxx',
        clientSecret: 'xxx',
        repo: 'xxx.github.io',
        owner: 'xxx',
        admin: ['xxx'],
        id: GenPageId()
      });
    }
    const gitalk = NewGitalk();

**Comment by booxood** [comment]
#212  similar

**Comment by XboxYan** [comment]
I aplly it  https://xy-ui.codelabo.cn/docs
