### ISSUE TITLE
chrome chromium 在编辑文字时体验差

### ISSUE THREAD

**Issue by nierunjie** [gitalk/gitalk#199]
在编辑时，背景会暗下来，仅突出输入框。
测试发现firefox和safari可以很流畅
但是在chrome内编辑时（Linux 和 Windows），整个过程体验很差，从点击输入框到仅突出输入框这个过程会多次卡顿，输入时整个页面会暗下来，停止输入大概一秒后才会恢复到预期的样子
请问能否去掉背景暗下来，或者该如何修改代码屏蔽这个特效

**Comment by zhuSilence** [comment]
我也发现了，确实有点怪异。

**Comment by booxood** [comment]
@nierunjie @zhuSilence zhu   有个配置项 `distractionFreeMode `

**Comment by nierunjie** [comment]
@booxood 删掉这个配置项可以起作用，仅仅设置成false还是无效
