### ISSUE TITLE
301重定向之后，通过https协议请求又出现401

### ISSUE THREAD

**Issue by iNiL0119** [gitalk/gitalk#200]
之前通过Cname绑定github仓库，http请求没问题，但是nginx设置了重定向并且将解析从Cname改为A解析之后，通过https请求就出现了401，而且github认证地址已经改为https协议

**Comment by iNiL0119** [comment]
难道需要使用gitalk的前提是需要cname解析吗？

**Comment by iNiL0119** [comment]
又可以了，本来是401，同时有些min.js和css文件出现500，后来将nginx的listen 443 ssl http2;的ssl和http2给去掉，重新部署，昨天一直不行，今天过来刷新看看还是不行，但是过了一会又可以了

**Comment by iNiL0119** [comment]
每次部署之后，都会出现，过个几十分钟后有没问题了，和github pai不稳定有关系？

**Comment by booxood** [comment]
是不是因为缓存

**Comment by iNiL0119** [comment]
@booxood 现在一切正常，部署之后也没问题了

**Comment by cqliulei** [comment]
> 之前通过Cname绑定github仓库，http请求没问题，但是nginx设置了重定向并且将解析从Cname改为A解析之后，通过https请求就出现了401，而且github认证地址已经改为https协议

解决了吗？我也一直出现401问题……

**Comment by booxood** [comment]
@cqliulei  401 相关问题可以参考 #183 里的评论，或者贴出自己的配置。
