### ISSUE TITLE
如何将设置评论提醒，如没有此功能建议完善

### ISSUE THREAD

**Issue by MakerGYT** [gitalk/gitalk#201]
如何在文章发生评论时提醒站长，如通过邮箱，或是提供接口将评论推送到站长某个服务端接收由站长自己做消息转发提醒。或者是github的issue本身有这样的功能或接口，劳烦告知

**Comment by nierunjie** [comment]
watching

**Comment by leafney** [comment]
可以使用钉钉提醒，方便好用 https://www.itfanr.cc/2018/09/17/hexo-add-gitment-review-system/#%E6%9C%89%E6%96%B0%E7%9A%84Issues%E6%97%B6%E5%8F%91%E9%80%81%E9%92%89%E9%92%89%E6%8F%90%E9%86%92

**Comment by booxood** [comment]
参考上面几位的回答。

**Comment by booxood** [comment]
这个 issue 关闭了，也欢迎还有其他办法的同学继续留言。
