### ISSUE TITLE
Gitalk 一直处于加载

### ISSUE THREAD

**Issue by pengliangs** [gitalk/gitalk#202]
您好，在我引入gitalk的blog中打开页面一直loading显示 “Gitalk 加载中 ...”

以下是我的操作

### oauth 信息

![image](https://user-images.githubusercontent.com/24536767/49267576-29e5d500-f496-11e8-9727-c50dc79843e5.png)

### gitalk使用

```javaScript
<div id="container"></div>
<link rel="stylesheet" href="/assets/gitalk/gitalk.css">
<script src="/assets/gitalk/gitalk.min.js"></script>
<script>
    var gitalk = new Gitalk({
        clientID: '{{ site.comments.clientId }}',
        clientSecret: '{{ site.comments.clientSecret }}',
        repo: '{{ site.comments.repo }}',
        owner: '{{ site.comments.owner }}',
        admin: ['{{ site.comments.owner }}'],
        id: '{{ page.title }}',
        labels: ['gitalk'],
        perPage: 50,
    })
    gitalk.render('container')
</script>
```

### 打开页面

![image](https://user-images.githubusercontent.com/24536767/49267679-8fd25c80-f496-11e8-85b9-1f6d202066d7.png)

测试地址：https://pengliangs.github.io/gitalk/%E6%B5%8B%E8%AF%95gitalk.html

**Comment by booxood** [comment]
你的页面上为什么是这样的
![image](https://user-images.githubusercontent.com/2151410/49270012-bb5b4400-f4a2-11e8-8e30-54897ab95d5a.png)

**Comment by booxood** [comment]
👌

**Comment by talengu** [comment]
> @booxood 谢谢，已经找到原因是vue框架，在创建实例块时会将<script>清除

我也遇到了这个问题，请问怎么修改的？

https://talengu.github.io/public/2021/04/02/math_AHP/
