### ISSUE TITLE
gitak获取不到评论...?

### ISSUE THREAD

**Issue by cgstudios** [gitalk/gitalk#21]
刚开始再博客上评论可以显示评论内容，过一段时间就不能显示评论内容了。而存放评论的issues下有评论，但博客上获取不到......

**Comment by cgstudios** [comment]
依然显示0条评论

**Comment by booxood** [comment]
可以发一下博客地址看下吗？

**Comment by cgstudios** [comment]
@booxood 
![cgstudios-gitalk](https://user-images.githubusercontent.com/22955150/29850789-aeefbcbc-8d62-11e7-9809-a2981505d595.png)
图中请求的是issue#46,而存放了评论的是issue#49,所以此时的comments字段为空，所以获取不到评论。
如果请求的是issue#49就能获取到评论
所以问题就是，它给同一篇文章开了2个issue,每次会请求不同的issue,评论为空的issue请求几率更大

**Comment by booxood** [comment]
当匹配到多个 issue 时，会取第一个，你可以把 `#46` 关闭掉来避免你现在遇到的问题。

**Comment by booxood** [comment]
另外，这两个 issue 的 label 其实是不一样的
`https://cgspace.date/2017/08/20/gitalk/2017-08-20-gitalk-comment-use/#more`
`https://cgspace.date/2017/08/20/gitalk/2017-08-20-gitalk-comment-use/`

**Comment by cgstudios** [comment]
原来是我自己url的原因.......ok, @booxood ,谢谢大佬了啊
