### ISSUE TITLE
一直给我发消息，怎么设置不发

### ISSUE THREAD

**Issue by fastspringcloud** [gitalk/gitalk#213]
我在https://gitalk.github.io/中发了一条消息，测试，然后每天都给我邮件发送消息，怎么设置才能不发
，我已经在这个网站中，把我的评论删了，还是再发邮件，求解，谢谢

**Comment by meteorlxy** [comment]
unsubscribe

**Comment by booxood** [comment]
抱歉，这个跟 GitHub 的 issue 相关提醒有关。

正常来说，你取消 issue 的订阅后，没有再 @你 的消息，是不会再收到相关邮件提醒了。
