### ISSUE TITLE
评论heart功能接口404

### ISSUE THREAD

**Issue by Leosocy** [gitalk/gitalk#216]
点击💗调用github v3api时会报404，包括[官网](https://gitalk.github.io/)上的此功能同样会报错。

**Comment by booxood** [comment]
https://gitalk.github.io/ 上的点赞用不了，我怀疑是因为回复数太多了。。。
你可以找一个别人的回复数少的试下，看看是不是还是404

**Comment by Leosocy** [comment]
> https://gitalk.github.io/ 上的点赞用不了，我怀疑是因为回复数太多了。。。
> 你可以找一个别人的回复数少的试下，看看是不是还是404

刚刚试了下又可以了，很迷，之前报错是commentID不存在，不知道github抽什么疯。
