### ISSUE TITLE
Incorrect comment formatting for email replies.

### ISSUE THREAD

**Issue by Liam0205** [gitalk/gitalk#224]
Hi the team, 

Great appreciation is here to show to you for your excellent work on `Gitalk` project.

Gitalk works well on my [blog](https://liam.page), except for the formatting for email replies. Thus the issue.

Since Gitalk is by dint of GitHub issue, GitHub may send emails to participates of the related issues. When these participates reply the email, his/her reply would be posted on the issues (figure 1), and then be synchronized to the bound blog post (figure 2).

![figure 1](https://user-images.githubusercontent.com/3348485/51580282-ee4c1200-1efe-11e9-99a9-efc518de4f3e.png)

![figure 2](https://user-images.githubusercontent.com/3348485/51580297-f86e1080-1efe-11e9-9586-b20944603e53.png)

As you could see, Gitalk gives incorrect formatting for the comment from email. Please consider to check and fix it.

**Comment by garrettbryan** [comment]
Checking the HTML, there are classes on the divs can be used to toggle the content visibility. This would match the native Github UI.
![image](https://user-images.githubusercontent.com/8527386/51988184-13e29980-2472-11e9-85bb-fc52d661d5a1.png)

**Comment by garrettbryan** [comment]
The ellipses following the response message is the element that controls visibility of the extended email message in Github's UI.

![image](https://user-images.githubusercontent.com/8527386/51988468-b864db80-2472-11e9-8a9e-4fdab6fcde85.png)

**Comment by garrettbryan** [comment]
I tracked the issue down.
1. The css from package github-markdown-css is incomplete.
2. Add a function to the span.email-hidden-toggle to toggle the class "expanded" on div.email-hidden-reply element.

**Comment by booxood** [comment]
@Liam0205 released v1.6.0 can fix.

**Comment by Liam0205** [comment]
@booxood 

Thanks. Currently (`1.6.0`), it shows like this:

![image](https://user-images.githubusercontent.com/3348485/74704541-ae637580-524b-11ea-9b3f-7b0d2cf216a0.png)
