### ISSUE TITLE
无法为多篇文章初始化评论。

### ISSUE THREAD

**Issue by sunu11** [gitalk/gitalk#225]
在没有任何issue的情况下，登录评论。完成当前文章的初始化。创建issue
之后无法为其他文章初始化，每次均为第一次创建的内容：
![image](https://user-images.githubusercontent.com/23350775/51894166-0978bf00-23e2-11e9-97eb-acb6e9b00e2e.png)

id也经过了md5处理。求助原因。
并且其他访问者访问文章无法评论，显示不存在issue。

**Comment by booxood** [comment]
id 是什么？

**Comment by sunu11** [comment]
> id是什么？是不是重复了？

id: md5( location.pathname )
同一篇文章访问一下就创建新的issue了
今天访问又创建了。
https://api.github.com/repos/sunu11/blog-comment/issues/58/comments

**Comment by sunu11** [comment]
不过我的文章访问连接是这样的：
![image](https://user-images.githubusercontent.com/23350775/51962846-76e92600-249c-11e9-928a-7b0fcf44b5ef.png)

![image](https://user-images.githubusercontent.com/23350775/51962853-7ea8ca80-249c-11e9-994e-93e4db2c6dd2.png)
有影响么？
另外这个也感觉有问题：
![image](https://user-images.githubusercontent.com/23350775/51962977-f119aa80-249c-11e9-8250-a0352c066f96.png)

**Comment by booxood** [comment]
> 同一篇文章访问一下就创建新的issue了

每次访问的链接地址是一样的吗？如果不一样，就会又创建。

**Comment by sunu11** [comment]
是一样的

**Comment by booxood** [comment]
@sunu11 问题还在吗？issue 先关闭了，如果问题还在，麻烦提供一下 blog 地址，方便直接上去看下问题。
