### ISSUE TITLE
邮件内容

### ISSUE THREAD

**Issue by allenfrostline** [gitalk/gitalk#228]
有没有办法customize邮件内容，使得可以一键到达blog对应的帖子而不是github的issue页？

**Comment by booxood** [comment]
`customize邮件内容` 哪里的邮件内容？

**Comment by allenfrostline** [comment]
@booxood 默认是github的邮件通知。

**Comment by booxood** [comment]
@allenfrostline 不行，邮件是由 GitHub 后台发送的，无法自定义。
