### ISSUE TITLE
Gitalk的评论页面出现在主页

### ISSUE THREAD

**Issue by Disappear9** [gitalk/gitalk#230]
描述
安装后Gitalk出现在主页，且 `comments: false` 设置失效

主题 
yilia

安装过程 
https://github.com/litten/hexo-theme-yilia/pull/784

示例
https://zgjjj.github.io/

**Comment by vkkevin** [comment]
我也遇到了这样的问题，comments: false 好像对这个是无效的

主题：
next

**Comment by booxood** [comment]
这个应该跟使用的主题有关吧
