### ISSUE TITLE
issue reopen后历史评论没有了，如何重新显示历史评论？

### ISSUE THREAD

**Issue by liheyuting** [gitalk/gitalk#235]
Hexo blog有一条issue不小心关闭了issue，reopen之后，历史评论不见了，我应该怎么做，把历史评论显示出来？

**Comment by booxood** [comment]
@liheyuting issue 的 label 不要改动，然后把后面为该 blog 生成的 issue 关闭，不然有多个 issue 被匹配。

**Comment by liheyuting** [comment]
谢谢
