### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by gitHber** [gitalk/gitalk#238]
## gittalk配置
  
![image](https://user-images.githubusercontent.com/22513044/54105647-a5004500-440e-11e9-832d-f2bbb48dca87.png)
## gittalk错误
![image](https://user-images.githubusercontent.com/22513044/54105689-be08f600-440e-11e9-940d-517902823419.png)
![image](https://user-images.githubusercontent.com/22513044/54105706-d11bc600-440e-11e9-9298-51566ff5ebdf.png)
> 看了很多错误解决，我这个配置应该是没问题的，但是还是会出现`Error: Not Found`这个错误，gittalk版本是1.5.0

**Comment by Henton** [comment]
我看现在你的blog-ghost仓库不存在，是后来删除了吗？

**Comment by Q-Angelo** [comment]
@gitHber 
踩了很对坑 终于解决了 你可以参考下 https://www.nodejs.red/#/tools/docsify

**Comment by goldenspider** [comment]
应该是你92行填的仓库不存在，要使用你已经建好的名字，这样，评论会存到该仓库的issue下

**Comment by holdlg** [comment]
没有找到仓库，修改一下repo的写法，如下：

`repo: 'githber/blog-ghost'`

**Comment by booxood** [comment]
应该是楼上同学说的问题。

**Comment by booxood** [comment]
issue 先关闭，有问题再打开。
