### ISSUE TITLE
labels 是否可以考虑去除id

### ISSUE THREAD

**Issue by huixisheng** [gitalk/gitalk#24]
`id`如果默认为`location.href`，也看到凹凸博客的加密的字符串，去看`issus`的时候长长的的`label`显得很不雅观，建议使用`tags`(当然这个可以自行配置)

**Comment by booxood** [comment]
`tags` 是指的什么？

**Comment by huixisheng** [comment]
就是文章的标签

**Comment by booxood** [comment]
可以把文章的 `tags` 设置到 `labels`

`id` 是为了唯一标示文章的
