### ISSUE TITLE
gittalk功能失效，授权登录后，一直加载。

### ISSUE THREAD

**Issue by sanshiliuxiao** [gitalk/gitalk#240]
### 未登录前

![](https://i.loli.net/2019/03/17/5c8dc6c20db1e.png)

### 使用 GitHub 登录后，一直加载，直到报错。

![](https://i.loli.net/2019/03/17/5c8dc6c22bc88.png)

### 点击 报错链接 得到的信息

![](https://i.loli.net/2019/03/17/5c8dc6c1f2034.png)

`Missing required request header. Must specify one of: origin,x-requested-with`

### 同时 我还让我朋友，从他那里登录， 结果也是一样的结果

![](https://i.loli.net/2019/03/17/5c8dc7c51cc9a.png)

**Comment by iarchean** [comment]
遇到同样问题，刚提了个 issue，就看到这个了。

**Comment by sanshiliuxiao** [comment]
> 遇到同样问题，刚提了个 issue，就看到这个了。

嗯嗯，昨天就遇到这样的情况了，不知道仓库管理者什么时候会解决。

**Comment by sanshiliuxiao** [comment]
功能好像恢复正常了，我关闭这个issues吧
