### ISSUE TITLE
proxy参数的作用是什么呢

### ISSUE THREAD

**Issue by Henton** [gitalk/gitalk#242]
proxy是使用gatekeeper代理吗？

**Comment by booxood** [comment]
@Henton 不是。默认是使用的 `https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token.`。proxy的作用是通过代理访问 https://github.com/login/oauth/access_token 避免跨域，更新详情看[这里](https://github.com/isaacs/github/issues/330)。

**Comment by WeiZhixiong** [comment]
如果你的站点使用了 nginx ，可以添加一个 location，
然后把 proxy 换成你自己的地址如 `https://example.com/login/oauth/access_token` 。

location 配置：
```
        location = /login/oauth/access_token {
            proxy_set_header Connection "";
            proxy_http_version 1.1;
            proxy_ssl_server_name on;
            proxy_ssl_protocols TLSv1.1 TLSv1.2;
            proxy_pass https://github.com;
        }
```
