### ISSUE TITLE
error: not found

### ISSUE THREAD

**Issue by angelasubi** [gitalk/gitalk#246]
![image](https://user-images.githubusercontent.com/20948536/55795973-82d81080-5afb-11e9-9249-958b43828de4.png)
我没有部署github.io 这个 新建了一个 repo
然后

gitalk:
  enable: true
  client_id: xxx
  client_secret: xxx
  repo: github.com/angelasubi/blogtalk
  owner: angelasubi
  admin: angelasubi

id 和secret无语 显示not found user这个请求没过  请教一下这是为什么

**Comment by Henton** [comment]
repo: github.com/angelasubi/blogtalk改成repo: blogtalk试一下呢

**Comment by angelasubi** [comment]
> blogtalk

![image](https://user-images.githubusercontent.com/20948536/55853585-60460600-5b94-11e9-8f33-c860087200da.png)
改成repo:blogtalk以后变成这样。

**Comment by Henton** [comment]
用angelasubi这个账号登录一下就OK了，需要用admin中的一个账号登录一下来初始化

**Comment by angelasubi** [comment]
> 用angelasubi这个账号登录一下就OK了，需要用admin中的一个账号登录一下来初始化

我初始化了。但是用别的电脑朋友的账号是error network 不知道为什么
我的地址是http://www.longye.xyz 你看下是不是有问题？

**Comment by Henton** [comment]
![image](https://user-images.githubusercontent.com/20090790/55856797-f3376e00-5b9d-11e9-987a-3f9613bd074a.png)我这里没问题的

**Comment by Henton** [comment]
你朋友之前查看过你的网站的话，让他换个浏览器试下，可能是缓存原因

**Comment by angelasubi** [comment]
> 你朋友之前查看过你的网站的话，让他换个浏览器试下，可能是缓存原因

谢谢了朋友完美搞定～

**Comment by Henton** [comment]
不客气

**Comment by holdlg** [comment]
没有找到仓库，修改一下repo的写法，如下：

`repo: 'angelasubi/blogtalk'`

**Comment by booxood** [comment]
感谢楼上热心答疑的同学

问题解决了，那 issue 就关闭了。
