### ISSUE TITLE
切换页面「url改变」但是gitalk没有更新加载新的评论内容，没有改变

### ISSUE THREAD

**Issue by Hongwing** [gitalk/gitalk#248]

**Comment by Hongwing** [comment]
gitalk-`options`显示id已经更新，但是内容并未更新

**Comment by Hongwing** [comment]
resolve
- dom刷新一遍

**Comment by Hideer** [comment]
@Hongwing 你好你有没有遇到开启评论的时候用户登录直接跳首页的问题

**Comment by Hongwing** [comment]
> @Hongwing 你好你有没有遇到开启评论的时候用户登录直接跳首页的问题

我一开始有遇到过，原因是：重定向地址有误无法返回之前的登录时所在页面「我得具体原因是因为页面URL太长,我截取一部分后解决问题」

**Comment by Hideer** [comment]
你是使用过https的么，我开始还以为，是我使用https的原因，因为我在本地开发环境直接使用本地ip是可以的，我回去试试，将标题缩短试试，谢谢

**Comment by booxood** [comment]
👍 问题解决了，那 issue 就关闭了。
