### ISSUE TITLE
提高移动端兼容性

### ISSUE THREAD

**Issue by tiexo** [gitalk/gitalk#25]
我在自己手机上测试了
- 安卓UC最新版浏览器
- 魅族自带浏览器

均不显示评论区...和gitment一样

![20170913213951](https://user-images.githubusercontent.com/8164505/30381850-2cc178ce-98d0-11e7-84cd-0f0a70196cf6.jpg)

但是我曾使用别人修改后的版本，解决了这个问题
可以参考下：https://github.com/imsun/gitment/pull/52

**Comment by booxood** [comment]
@tiexo 已经修复，感谢反馈。
