### ISSUE TITLE
提示出现Error: Invalid request. For 'items', nil is not a string or object..

### ISSUE THREAD

**Issue by soloopooo** [gitalk/gitalk#251]
就像这样：
![image](https://user-images.githubusercontent.com/36123081/56464144-a5c8c580-6415-11e9-87ec-493cd38f6d64.png)

**Comment by FoamValue** [comment]
这个问题，后来解决了么？

**Comment by soloopooo** [comment]
解决了 
后来发现是id:location.xxx(xxx设置出现问题）的问题。
我设置错了

**Comment by booxood** [comment]
😄问题解决了，那 issue 就关闭了。
