### ISSUE TITLE
有加入Hexo博客的简单方法么

### ISSUE THREAD

**Issue by newdee** [gitalk/gitalk#26]
之前用的来必力，这两天貌似挂了。后来试了一下Gitment，不过有些麻烦，每篇文章得手动初始化才能创建一个Issue，才能评论。这个我看了下demo，感觉界面不错，不过有加入hexo博客的比较方便的方法么，像Next主题那种的？

**Comment by tiexo** [comment]
主题没适配的话就要手动添加代码了...

**Comment by mamboer** [comment]
@newdee 凹凸实验室的官网就是hexo的，也用Gitalk，你可以参考下，两个步骤：

1. 建一个comment.swig页面片（有的话可以改下）

https://github.com/o2team/o2team.github.io/blob/v2/themes/lattice/layout/_partial/common/comment.swig

2. 在你主题的配置文件里面加入gitalk的配置即可

https://github.com/o2team/o2team.github.io/blob/v2/themes/lattice/_config.yml#L35

**Comment by FETE-CH** [comment]
@mamboer 还是没有显示啊，都不知道改怎么办了

**Comment by newdee** [comment]
@mamboer @FETE-CH @tiexo 恩，我花了点时间，自己移植到了hexo的Next主题上，其他的主题大同小异，凹凸实验室那个不大具有普遍性，直接这样改不大便于管理，而且很多主题是显示不出来的。具体过程见我的博客:
http://newdee.cf/posts/4da30c7/
不大懂前端，所以有问题还希望各位指出来。

**Comment by mamboer** [comment]
@newdee `gitalk`初始化的逻辑是：你打开页面的时候，如果已登录并且登录名在`admin`配置项内，就会自动初始化（不用手工点某个按钮）当前页面的评论。所以做不到一次性初始化所有的文章哈。

**Comment by newdee** [comment]
@mamboer 对的，我明白你的意思，不过由于以前的文章比较多，所以有点麻烦，不过我还是手动初始化了的，毕竟这个还比较好看吧，以后写博客就方便一些了。不过还有个小问题，在博客主页会有个错误”index.js:18 Uncaught Error: Container not found, document.getElementById: gitalk-container“，这个应该是主页没有设置这个容器的，只是在评论系统里添加了，不知道为什么主页会有这个问题。。。

**Comment by ElderJames** [comment]
我加入到了这个模版，详细看这个pr https://github.com/viosey/hexo-theme-material/pull/554

**Comment by mamboer** [comment]
@newdee 你检查下主页是不是也把gitalk的js代码也加进去了，如果是的话需要检查下引入gitalk的写法是否合理。

**Comment by newdee** [comment]
@mamboer 谢谢提醒，我当时也觉得是，但是感觉写的没问题，后来发现是忘记加判断comments了，还是当时不够仔细，原文已经[修正](https://newdee.cf/posts/4da30c7/)
再次感谢Gitalk提供的帮助。
