### ISSUE TITLE
[Question] 能否将issue放在自己的private repo里面

### ISSUE THREAD

**Issue by OliverLew** [gitalk/gitalk#266]
我将原public repo变为private后, 显示"Error: no access token".
note: 我使用了另一个repo来放issue, 上面是将放issue的repo变为private.

现在的版本能否解决这个问题? 不能的话, 可不可以实现?

**Comment by ahonn** [comment]
如果其他人能看到你的 private repository，意味着其他人拥有你的 access token，也就是说其他人能够拿着 token 通过 Github 的 API 来进行修改/删除操作。所以即使能够实现，那也是不安全的。

**Comment by OliverLew** [comment]
> 如果其他人能看到你的 private repository，意味着其他人拥有你的 access token，也就能够拿着 token 通过 Github 的 API 来进行修改/删除操作。所以即使能够实现，那也是不安全的。

有道理啊，没仔细想过，谢谢给我解释。那还是建个小号吧，issues太多了心烦 ：）
