### ISSUE TITLE
gitalk 是否不再维护了？

### ISSUE THREAD

**Issue by ahonn** [gitalk/gitalk#272]
看到已经堆积了很多的 issue & pull requests，最后一次 commit 也是五个月前

**Comment by liuyib** [comment]
也许吧，看样子是不想维护了，从gitment到gitalk

**Comment by Qin-Dong** [comment]
开源就是这样，兴趣消磨干净后人就玩失踪了！

**Comment by javakam** [comment]
有没有其他的呢...o(︶︿︶)o 唉

**Comment by Dup4** [comment]
> 有没有其他的呢...o(︶︿︶)o 唉

https://github.com/utterance/utterances 这个好像还在维护。

**Comment by booxood** [comment]
下半年我有点忙，不好意思哈~ 

会尽快找到维护者一起参与进来，保证项目的活跃！

感兴趣的小伙伴也可以主动联系，开源本来就是希望大家都能参与进来~
