### ISSUE TITLE
hexo 主题next无法自动创建issue,创建issue接口报403

### ISSUE THREAD

**Issue by kyo7701** [gitalk/gitalk#280]
![image](https://user-images.githubusercontent.com/8190912/62426334-030f2b00-b716-11e9-93b3-2b3800c830f3.png)

**Comment by kyo7701** [comment]
主题配置:
![image](https://user-images.githubusercontent.com/8190912/62426353-42d61280-b716-11e9-9730-0409e37094d3.png)

**Comment by kyo7701** [comment]
swig配置:
![image](https://user-images.githubusercontent.com/8190912/62426364-6731ef00-b716-11e9-8ff6-ea2053af07e7.png)

**Comment by kyo7701** [comment]
回调配置![image](https://user-images.githubusercontent.com/8190912/62426379-a52f1300-b716-11e9-92a2-79a3ce64c0cb.png)

**Comment by kyo7701** [comment]
求问大佬应该怎么排查呢？

**Comment by lidezheng** [comment]
在Settings Developer settings 里面 创建 OAuth Application，不是GitHub Apps！！！，我也是踩坑后才知道

**Comment by kyo7701** [comment]
> 在Settings Developer settings 里面 创建 OAuth Application，不是GitHub Apps！！！，我也是踩坑后才知道
:scream:解决了，确实是这样

**Comment by kyo7701** [comment]
感谢！
