### ISSUE TITLE
删除评论后，页面上显示评论数量不会变化

### ISSUE THREAD

**Issue by jostyee** [gitalk/gitalk#29]
没有-1

**Comment by booxood** [comment]
@jostyee 请问你是怎么删除评论的？

**Comment by jostyee** [comment]
@booxood Sorry，居然漏掉了通知。
走GitHub删除的，现在1.1.4发现个更大的问题，我发了评论后评论数没变，还是0。。

<img width="334" alt="screen shot 2017-12-07 at 4 10 13 pm" src="https://user-images.githubusercontent.com/88564/33704878-266783d4-db69-11e7-9dcf-079d68f0ef03.png">

**Comment by booxood** [comment]
@jostyee 走GitHub删除的，Gitalk 的展示不会更新，不是实时的，需要刷新页面才行。
