### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by Uzay-G** [gitalk/gitalk#290]
Hey, I think there might be an issue answering this problem but I can't read the language. The comments on my site are working except for one page where users cannot comment and the only response is Error: Validation failed. Does anyone know how I can fix this?

**Comment by booxood** [comment]
Because GitHub limit `label` length must less 50. Please check options `id`.

**Comment by eastzq** [comment]
use title md5 and setvalue 2 id property
我的解决方法：使用标题或者唯一id的md5值，配置在初始化到id上
