### ISSUE TITLE
Gitalk支持匿名评论吗？

### ISSUE THREAD

**Issue by Qin-Dong** [gitalk/gitalk#296]
鉴于上GitHub还是有一定难度的，加上现在的验证机制在很多浏览器下无效，要注册一个GitHub帐号也挺费劲。而我们的页面针对的是行业内的普通网友，GitHub上的大咖们也不太会到我们的个人博客上去浪费时间，因此开放匿名评论我认为很有必要，很难想象有人会为了一个评论而去注册GitHub帐号，况且一般注册还成功不了。我印象中在哪看到过匿名评论，不知是gitalk还是gitment了。望高手支招！在此谢过！

**Comment by booxood** [comment]
不支持。

因为评论的数据最终都依托 GitHub 的 issue 进行记录存储。

**Comment by axiaoxin** [comment]
可以搞一个默认账号，匿名使用默认账号发布
