### ISSUE TITLE
目前还不支持回复功能吗

### ISSUE THREAD

**Issue by PandaraWen** [gitalk/gitalk#3]

**Comment by booxood** [comment]
不支持，但可以 @xxxx，这样可以收到提醒

**Comment by YanHuiLi** [comment]
希望完善一下吧。

**Comment by booxood** [comment]
Gitalk 展示的数据完全是基于 github issues 保存的，所以。。。 issues 不支持回复 Gitalk 也不好支持。

不知道有没有什么办法可以支持，欢迎讨论~

**Comment by ProfFan** [comment]
可以考虑加上简单的结构化数据，就像HTTP头

**Comment by booxood** [comment]
@ProfFan 可以具体的说明一下吗

**Comment by nasyxx** [comment]
@booxood Hi, 关于回复，咱有个想法，比如用引用的方式，把要回复的那个人说的引用一次。比如回复您之前的那段，可以这样：

---

> @booxood (或者 回复 @booxood )
> Gitalk 展示的数据完全是基于 github issues 保存的，所以。。。 issues 不支持回复 Gitalk 也不好支持。
> 不知道有没有什么办法可以支持，欢迎讨论~

回复内容xxxx

---

不知道这样感觉如何？

**Comment by booxood** [comment]
> @nasyxx 
> @booxood Hi, 关于回复，咱有个想法，比如用引用的方式，把要回复的那个人说的引用一次。比如回复您之前的那段，可以这样：
>
> ---
>
> > @booxood (或者 回复 @booxood )
> > Gitalk 展示的数据完全是基于 github issues 保存的，所以。。。 issues 不支持回复 Gitalk 也不好支持。
> > 不知道有没有什么办法可以支持，欢迎讨论~
> 
> 回复内容xxxx
> 
> ---
> 
> 不知道这样感觉如何？


感觉可以哦 😄 
有点类似邮件形式的回复

**Comment by ProfFan** [comment]
@booxood Just like
```
Comment-Reply-To: post_id
```

**Comment by booxood** [comment]
@ProfFan 这样展示上是可以做到，但点击 “加载更多” 时就会有点问题

**Comment by ProfFan** [comment]
@booxood 用 JavaScript parse 整个 thread 然后生成结构化的数据再渲染

**Comment by booxood** [comment]
@ProfFan 一开始就把所有数据都加载下来，然后重新组装，那 `perPage` 就没意义了，另外 Github 的接口限定最多一次只能加载100条数据。
