### ISSUE TITLE
评论自动订阅issue的问题

### ISSUE THREAD

**Issue by tiexo** [gitalk/gitalk#31]
我看了下 #15 里面有了一些讨论，现在有个想法不知道能不能实现

首先在gitalk里面有一个“回复”按钮
点击回复后会@该用户

另外如果我们取消订阅，被@还是会收到提醒，不被@则不会收到提醒
那么按照这个逻辑，只要我们取消了订阅，就是正常的评论提醒功能了

1.如果有人@你，你会收到邮件提醒，因为他是回复你的，你应该收到提醒
2.没有人@你，直接评论的，你不会收到提醒，因为这条评论和你没关系

所以只需要在评论后，自动取消订阅就可以不被骚扰了。
可以实现自动取消订阅么，或者在页面添加一个选项？

**Comment by tiexo** [comment]
还有个小问题，作为创建issue的博主，如果取消订阅了
别人评论你的文章应该不能收到提醒了....这样就无法及时的回复
所以，最好还是添加一个选项让用户自己选择....

但是个人觉得比较难实现啊，应该没有这样的接口吧...只能跳转到issue操作？
或者有没有其他办法简化或者引导这个过程呢

**Comment by booxood** [comment]
Github 好像还没有 `订阅` 或 `取消订阅` 的 API

**Comment by MHuiG** [comment]
[Github Notifications API](https://developer.github.com/v3/activity/notifications/)

[https://developer.github.com/v3/activity/notifications/](https://developer.github.com/v3/activity/notifications/)
