### ISSUE TITLE
图片加载比较慢

### ISSUE THREAD

**Issue by removeif** [gitalk/gitalk#313]
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2019/20191125224119.png)
如图，图片加了cdn，本应该比较快，但是img标签中src转换成了另一个路径，这是怎么处理的，能用原图作为src的value吗？
在线地址：https://removeif.github.io/self-talking/

**Comment by booxood** [comment]
@removeif 你这是把图片上传到 Github 了吧？ 你说的 `图片加了cdn` 是什么意思？

**Comment by booxood** [comment]
这个问题应该跟 Gitalk 没关系。先关闭了。
