### ISSUE TITLE
【需求】建议添加点赞功能

### ISSUE THREAD

**Issue by Leo-Mu** [gitalk/gitalk#33]
有回复功能，非常不错！
但是还缺一个对整个文章或者某条评论点赞的按钮。建议添加对页面、对每条评论的点赞按钮，按钮链接到 issue 中 Add your reaction 功能。

**Comment by booxood** [comment]
之前有考虑过是否添加点赞功能，最后觉得目前接口不能针对点赞数排序什么的，就不增加点赞功能了。

**Comment by Leo-Mu** [comment]
其实点赞不一定是为了排序啊，增加一种互动手段也是很有用的。而且 Github 的 Add your reaction 有这么好几个 reactions！其实本身也没有排序功能。
话说捣鼓了半天，我现在已经用上了呢！
https://qbug.cf/

**Comment by ashfinal** [comment]
点赞好有用的！建议添加

**Comment by calpa** [comment]
很有用的功能，建议增加。

**Comment by Chickking** [comment]
建议添加，GitHub 本来就有这个功能的。

**Comment by booxood** [comment]
发布了 v1.2.0，增加了点赞功能~

**Comment by Ir1d** [comment]
hi, 我想问下，现在可以给一个文章进行点赞吗？谢谢

**Comment by booxood** [comment]
@Ir1d 还不可以。现在只有针对每条评论进行点赞。

**Comment by Ir1d** [comment]
谢谢，最近有添加这个功能的计划吗 :smile: @booxood

**Comment by booxood** [comment]
@Ir1d 最近有点忙。。没计划。。

**Comment by small-panda** [comment]
统计评论数的还没做吗
