### ISSUE TITLE
还是issue重复问题

### ISSUE THREAD

**Issue by zhyjc6** [gitalk/gitalk#331]
css和js代码使用的是1.5.0版本，id使用id: `md5(location.pathname)`
但是在距上次生成issue大概十来分钟后再次刷新页面会生成一个重复的issue，该issue id（md5）值和原来不同（不再是当前文章的md5了）。并且删除该issue后留下原来的issue原来的评论不会被加载
我刚刚用gitalk，想知道大家都是手动添加issue的吗，为什么md5值会变？

**Comment by Mabbs** [comment]
你的博客不能自己生成id吗？

**Comment by booxood** [comment]
是不是你博文的 location.pathname 变了？

这块应该是不存在问题的，不然大家都没法用了。
