### ISSUE TITLE
About Error: Validation Failed, 422

### ISSUE THREAD

**Issue by Portgas-D-Asce** [gitalk/gitalk#335]
there are two reason:
1. id's length is more than 50(md5 is a good idea)
2. your page miss title, you need to add <title><%= page.title %></title> for your page
for the second reason, when you login as admin, there won't be an issue(but you can find a new label), leading to Error: Validation Failed, 422

**Comment by Chad97** [comment]
add config  file `title`

**Comment by Portgas-D-Asce** [comment]
> add config file `title`

no, html file includes head and body label and head label includes title label which you should add, so you should add <title><%= page.title %></title> in your layout file, for example head.ejs
