### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mousedown' of undefined

### ISSUE THREAD

**Issue by CodeHaotian** [gitalk/gitalk#337]
**当我在Chrome浏览器下点击登录GitHub，控制台会抛出如下异常无法正常跳转登录：**

Uncaught TypeError: Cannot read property 'mousedown' of undefined
    at Array.h (preact.js:96)
    at unhook (userscript.html?id=777f0d31-0b5d-4ad0-9812-993bcd54e24d:130)
    at HTMLButtonElement.unhook_f (userscript.html?id=777f0d31-0b5d-4ad0-9812-993bcd54e24d:125)
h @ preact.js:96
unhook @ userscript.html?id=777f0d31-0b5d-4ad0-9812-993bcd54e24d:130
unhook_f @ userscript.html?id=777f0d31-0b5d-4ad0-9812-993bcd54e24d:125

**Comment by CodeHaotian** [comment]
![image](https://user-images.githubusercontent.com/34121589/71458670-cc2dd480-27de-11ea-8c28-5cf770ba91bf.png)

**Comment by booxood** [comment]
@CodeHaotian 什么版本的 chrome 啊？是不是比较老的版本了？

看报错是 preact 里抛的，如果浏览器不兼容，那也没办法了。
