### ISSUE TITLE
特性请求：粘贴上传图片

### ISSUE THREAD

**Issue by ElderJames** [gitalk/gitalk#34]
利用github中issue的功能，粘贴上传图片并生成markdown链接。

**Comment by booxood** [comment]
@ElderJames Github 没有提供公开的上传图片接口，如果要实现粘贴上传图片，需要借助第三方的图床，所以，这一步还是让用户自己去选择合适的图床上传吧。

**Comment by booxood** [comment]
@xiazeyu 这样的编辑器太`重`了。
