### ISSUE TITLE
Any plan to support in-place editing/delete?

### ISSUE THREAD

**Issue by changtimwu** [gitalk/gitalk#341]
vssue [emphasize this](https://vssue.js.org/guide/#comparison-with-similar-projects) in its docs.

_Vssue can post, edit and delete comments. Gitment and Gitalk can only post comments._

**Comment by weiweitop** [comment]
hi guys,

  this is my dumb solution https://weiweitop.fun/about/ just for fun :smiley:

  https://weiweitop.fun/2019/08/10/静态博客评论系统的比较及选择/#vssue shows the steps

**Comment by booxood** [comment]
No plan. Welcome to PR. :wink:
