### ISSUE TITLE
hexo next主题中如何能够在副标题显示评论数了？

### ISSUE THREAD

**Issue by ehlxr** [gitalk/gitalk#35]
next主题中如何能够在副标题显示评论数了？如下图显示的效果
![image](https://user-images.githubusercontent.com/11313370/31713272-5fb1f82c-b3c3-11e7-8370-db2aef4c6224.png)

**Comment by booxood** [comment]
这好像跟 Gitalk 关系不大吧。。

**Comment by ehlxr** [comment]
集成到 next 主题时需要具有一个 item 属性的元素的属性 commentsCount 来展示评论数
![image](https://user-images.githubusercontent.com/11313370/31755959-e28399b0-b466-11e7-8e38-b09ac43d2113.png)
请问这个怎么在 Gitalk 中加上了？

**Comment by booxood** [comment]
Gitalk 目前没有提供这个值出来。

可以考虑增加类似 `window.GITALK_COMMENTS_COUNT` 这样的值便于第三方做展示。
