### ISSUE TITLE
Version 1.5.2 has not been upload to CDN correctly

### ISSUE THREAD

**Issue by Liam0205** [gitalk/gitalk#350]
Hi the team.

Base on the [diff](https://github.com/gitalk/gitalk/compare/71db14c2699d618307c86a08903201aeddaa91d0...bba1ff76de3c17b4083603a595bf454c92c0cfca) between `1.5.1^` and `1.5.2`, introduced by #346 , version 1.5.2 has not been upload to CDN (<https://cdn.jsdelivr.net/>) correctly.

Details:

* [x] <https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.js>
* [ ] <https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js>

Please kindly check this.

**Comment by Liam0205** [comment]
**UPDATE**

* [x] https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.js
* [ ] https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
* [x] https://cdn.jsdelivr.net/npm/gitalk@1.5.2/dist/gitalk.js
* [x] https://cdn.jsdelivr.net/npm/gitalk@1.5.2/dist/gitalk.min.js
* [x] https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.js
* [ ] https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js

**Comment by jerryc127** [comment]
it seen like https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js not update
