### ISSUE TITLE
Error: Network Error怎么解决

### ISSUE THREAD

**Issue by alienyan** [gitalk/gitalk#359]
前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
但是我是用别人的主题而且自带的gitalk插件，所以我也不会改。

**Comment by alienyan** [comment]
可以看看：https://qghost.gitee.io/blog/

**Comment by LiosWong** [comment]
我的也出现同样的问题

**Comment by zt-luo** [comment]
> 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> 但是我是用别人的主题而且自带的 gitalk 插件，所以我也不会改。

让主题作者更新啊

**Comment by alienyan** [comment]
> > 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> > 但是我是用别人的主题而且自带的 gitalk 插件，所以我也不会改。
> 
> 让主题作者更新啊

他们那边也不知道怎么回事，说过来找gitalk这边问

**Comment by zt-luo** [comment]
> 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.

这个问题可以通过更新到最新版本的gitalk来解决，让主题作者更新下即可。
另一个问题我也不懂，，，@alienyan

**Comment by alienyan** [comment]
> > 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> 
> 这个问题可以通过更新到最新版本的gitalk来解决，让主题作者更新下即可。
> 另一个问题我也不懂，，，@alienyan

最新不是1.6.0版吗，我确实是用最新版

**Comment by zt-luo** [comment]
> > > 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> > 
> > 
> > 这个问题可以通过更新到最新版本的 gitalk 来解决，让主题作者更新下即可。
> > 另一个问题我也不懂，，，@alienyan
> 
> 最新不是 1.6.0 版吗，我确实是用最新版

最新版是1.6.0，你之前是什么版本？我现在用的1.5.2，从1.5.0更新上来的时候是过了几天才没有收到邮件。

**Comment by alienyan** [comment]
> 最新版是1.6.0，你之前是什么版本？我现在用的1.5.2，从1.5.0更新上来的时候是过了几天才没有收到邮件。
就是1.6.0啊

**Comment by alienyan** [comment]
> > > > 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> > > 
> > > 
> > > 这个问题可以通过更新到最新版本的 gitalk 来解决，让主题作者更新下即可。
> > > 另一个问题我也不懂，，，@alienyan
> > 
> > 
> > 最新不是 1.6.0 版吗，我确实是用最新版
> 
> 最新版是1.6.0，你之前是什么版本？我现在用的1.5.2，从1.5.0更新上来的时候是过了几天才没有收到邮件。

就1.6.0啊

**Comment by zt-luo** [comment]
> > > > > 前几周一直给我发邮件说：Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.
> > > > 
> > > > 
> > > > 这个问题可以通过更新到最新版本的 gitalk 来解决，让主题作者更新下即可。
> > > > 另一个问题我也不懂，，，@alienyan
> > > 
> > > 
> > > 最新不是 1.6.0 版吗，我确实是用最新版
> > 
> > 
> > 最新版是 1.6.0，你之前是什么版本？我现在用的 1.5.2，从 1.5.0 更新上来的时候是过了几天才没有收到邮件。
> 
> 就 1.6.0 啊

好吧，那我不知道了。

**Comment by yeung66** [comment]
我将gitalk版本更新到最新后也出现了这个问题，虽然不会收到GitHub的邮件了，不过现在直接就Error: Network Error用不了

**Comment by alienyan** [comment]
> 我将gitalk版本更新到最新后也出现了这个问题，虽然不会收到GitHub的邮件了，不过现在直接就Error: Network Error用不了

我收到邮件还是能用的时候，现在用不了也就不发了

**Comment by zt-luo** [comment]
1.5.2版本的呢？

**Comment by alienyan** [comment]
> 1.5.2版本的呢？

这个没试过

**Comment by booxood** [comment]
`Network Error` 是因为你当前的网络访问 Github 出错了，因为什么原因，你们懂得。

升级到 `1.5.2` 之后的版本还会收到 `Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.` 的邮件，应该是因为有些之前访问过的用户有缓存，还是用的旧的版本。

**Comment by alienyan** [comment]
> `Network Error` 是因为你当前的网络访问 Github 出错了，因为什么原因，你们懂得。
> 
> 升级到 `1.5.2` 之后的版本还会收到 `Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated.` 的邮件，应该是因为有些之前访问过的用户有缓存，还是用的旧的版本。

我懂了，谢谢大佬

**Comment by Ghostwritten** [comment]
怎么办? gitalk network error?
