### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by Gunpowder-pixel** [gitalk/gitalk#379]
### 看了看其他和我相似的问题，发现配置都是对的，但是还是显示`Error: Not Found`
麻烦有空的大佬帮我看一下哪里有问题，多谢🙏
```
Application name:
gitalk

Homepage URL:
https://Gunpowder-pixel.github.io

Authorization callback URL:
https://Gunpowder-pixel.github.io
```
```
repo:"Gunpowder-pixel.github.io"
owner:"gitalk"
admin:["gitalk"]
```

**Comment by OliverLew** [comment]
`owner`和`admin`是用户名，直接看repo的地址：`github.com/owner/repo`。应该是这个问题

**Comment by Gunpowder-pixel** [comment]
> `owner`和`admin`是用户名，直接看repo的地址：`github.com/owner/repo`。应该是这个问题

emmmmm，还是没看明白大佬的意思

你说的`owner`和`admin`的用户名是指`Application name`的话，我设置的就是`gitalk`
还是说是指github账户的用户名？

`直接看repo的地址：github.com/owner/repo`

这句话实在看不懂，没有过这方面的经验

麻烦大佬了

**Comment by OliverLew** [comment]
不好意思，确实没说明白，我自己都看不懂了。。
owner和repo组成的这个地址`github.com/owner/repo`应该是你想要放置issue的仓库，admin是对这个仓库有写权限的用户名。通常owner和admin写自己的用户名。

其实，我觉得readme应该明确指出这一点，我也是很长时间想明白的。

**Comment by Gunpowder-pixel** [comment]
> 不好意思，确实没说明白，我自己都看不懂了。。
> owner和repo组成的这个地址`github.com/owner/repo`应该是你想要放置issue的仓库，admin是对这个仓库有写权限的用户名。通常owner和admin写自己的用户名。
> 
> 其实，我觉得readme应该明确指出这一点，我也是很长时间想明白的。

我改了下，大佬看是这样吗？
```
  var gitalk=new 
      Gitalk({clientID:"0058279042bf75c9553d",  
      clientSecret:"94aebb179015ab6f0ab4ab77b8ad3cd0ecf0d3d9",  
      repo:"github.com/Gunpowder-pixel/Gunpowder-pixel.github.io",  
      owner:"Gunpowder-pixel",  
      admin:["Gunpowder-pixel"],  
      id:(location.pathname).substring(0, 49),  
      distractionFreeMode:false});
  gitalk.render("gitalk-container");
```
不过还是显示`Error: Not Found`

折腾gitalk好几天了，心好累

**Comment by OliverLew** [comment]
repo只有`Gunpowder-pixel.github.io`，再试一下

**Comment by Gunpowder-pixel** [comment]
> repo只有`Gunpowder-pixel.github.io`，再试一下

换成`Gunpowder-pixel.github.io`后成功运行了

另外，虽然不显示`Error:Not Found`,但是显示`未找到相关的 Issues 进行评论`，然后一点登陆就跳转首页，后来去`OAuth Apps`里面把`Authorization callback URL`从`https://Gunpowder-pixel.github.io`改成博客绑定的域名，然后就正常了

看来问题就出在`owner`和`admin`，这两个得填对，多谢大佬帮助

**Comment by booxood** [comment]
> owner和repo组成的这个地址github.com/owner/repo应该是你想要放置issue的仓库，admin是对这个仓库有写权限的用户名。通常owner和admin写自己的用户名

确实这样说明下，容易理解（我以为都是这么理解 github 仓库地址的。。
