### ISSUE TITLE
请问支持已有评论导入吗？支持的话该如何配置呢？

### ISSUE THREAD

**Issue by qianmofeiyu** [gitalk/gitalk#38]
我已经有一个项目用了 gitment，但是后面发现他的局限很大，想问下是否支持已有的 issue 直接导入呢？可以的话该如何配置呢？

**Comment by qianmofeiyu** [comment]
@booxood @mamboer 麻烦解答一下。

**Comment by booxood** [comment]
@qianmofeiyu 支持。都是基于 Github issue。

根据 Gitalk 需要的配置项，把你之前 gitment 配置的对应配置项拷贝过来。

**Comment by qianmofeiyu** [comment]
我已经把 gitment 的配置复制过去，打开以后还是需要初始化 issue

**Comment by qianmofeiyu** [comment]
[代码](https://github.com/gitalk/gitalk/blob/1143d417aa6a28ac08cb56456ef05042c15fc3ec/src/gitalk.jsx#L80) 主要是这个条件进不去，打开评论的 url 没有查询参数不知道这个判断用意。

**Comment by booxood** [comment]
这里的 `query.code` 是 github auth login 后返回的

**Comment by booxood** [comment]
@qianmofeiyu 你的网站方便发出来看下吗？

**Comment by qianmofeiyu** [comment]
https://devrsi0n.github.io/React-2048-game/comments， 我还在弄，目前是重新初始化了一个新的 issue

**Comment by qianmofeiyu** [comment]
就是说 label 要完全一样？

**Comment by qianmofeiyu** [comment]
[gitalk 代码](https://github.com/devrsi0n/React-2048-game/blob/a049cf41f447d9fdd0ae243c4e3f257f7fd4431f/src/components/Comments/index.js#L7)

**Comment by booxood** [comment]
![image](https://user-images.githubusercontent.com/2151410/32041370-6b37c1fe-b9f9-11e7-9799-3d0ba6c1b16e.png)

对。是通过 `label` 来匹配 Issue 的。你可以把下面的这个 issue 的 label 改成跟上面的一样，然后再关闭上面那个 issue。

**Comment by qianmofeiyu** [comment]
labels 标签以及改成完成一样了，还是不行。
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32697970/32043091-56d20c06-ba6c-11e7-9312-728f6ff6d88d.png">

**Comment by qianmofeiyu** [comment]
这是从 source 面板打开的配置 
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/32697970/32043216-ad0fbd8e-ba6c-11e7-99ad-0bddfe7b08fb.png">

**Comment by booxood** [comment]
因为 `https://cors-anywhere.herokuapp.com/` 这个服务挂了。。

**Comment by qianmofeiyu** [comment]
😂 那有别的跨域网站可以用吗？

**Comment by booxood** [comment]
改成 `proxy: https://gh-oauth.imsun.net/` 试试

**Comment by qianmofeiyu** [comment]
好像不是这个问题。
<img width="507" alt="image" src="https://user-images.githubusercontent.com/32697970/32044266-b0ab8d6c-ba6f-11e7-8f72-4b7241c1003f.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/32697970/32044318-d0610452-ba6f-11e7-90a1-17e90114a7e2.png">
第二个请求里面的 labels 自动添加了当前页面的 location.href ，是这个问题吗？

**Comment by qianmofeiyu** [comment]
@booxood 我把这个 label 添加到 issue 就可以了，多谢。
