### ISSUE TITLE
未找到相关的 Issues 进行评论

### ISSUE THREAD

**Issue by LeeMaster** [gitalk/gitalk#381]
Travis 构建，仓库已经初始化完成了相关 issue 为啥还是找不到？？？？？

**Comment by LeeMaster** [comment]
![image](https://user-images.githubusercontent.com/17953717/81242303-544ea100-903f-11ea-872b-5393f3c030d3.png)

**Comment by LeeMaster** [comment]
我测试了以后，只要把这里的Gitalk 去掉以后就能获取到数据，但是没有找到配置的地方？？？

**Comment by booxood** [comment]
能完整详细的再描述下吗？

**Comment by LeeMaster** [comment]
> 能完整详细的再描述下吗？

Gittalk 插件默认参数内会有一个 Gittalk，然后我生成的时候没有Gittalk 标签，所以就GG了，这个不可以自己配置吗

**Comment by booxood** [comment]
可以配置 labels 修改标签，默认是：['Gitalk']。

**Comment by booxood** [comment]
@jousindea 你这个情况，估计是网络原因。

**Comment by 1042004021** [comment]
同样的问题 已经得到解决了吗
