### ISSUE TITLE
引用了latest的Gitalk, 但是登陆时/点击comment栏会自动跳转到archive页面

### ISSUE THREAD

**Issue by yougikou** [gitalk/gitalk#382]
所有配置是按readme来的.
这是我的repo
https://github.com/yougikou/yougikou.github.io

现象是如果我不debug页面, 点击"登录"就会跳转到blog archive page.
如果debug, 就能顺利进行login.(这个现象让我怀疑人生啊, 还以为自己在做量子实验 - 观察决定结果)
成功login后,点击leave comment, 又会自动跳转到archive page.

Google了好久没有相关信息.
我折腾了几次, 一直搞不定. 只能来这里碰碰运气.

**Comment by yougikou** [comment]
自己解决了.在这里更新一下.
原因有可能是js加载顺序或者document查找时候的问题.
如果有熟悉的朋友,希望帮助补充说明一下.

一开始, 我只是把div层和js随便放在了page的最下方.
现在我把div的位置调整到post div里面后 - 都正常了.

**Comment by booxood** [comment]
自己解决了！真棒！

js 一般放在最后的啊。
