### ISSUE TITLE
Error: Network Error，并且点登陆也报错，输入也报错

### ISSUE THREAD

**Issue by linzefan0612** [gitalk/gitalk#387]
``` js
 let gitalk = new Gitalk({
      clientID: "生成的clientID",
      clientSecret: "生成的clientSecret",
      repo: "blog", // 仓库名
      owner: "linzefan0612",
      admin: ["linzefan0612"],
      id: title,
      distractionFreeMode: false
    });
```
![1](https://user-images.githubusercontent.com/52768739/83961106-967b3480-a8c2-11ea-8a95-f28fdc87b227.png)
![2](https://user-images.githubusercontent.com/52768739/83961109-a1ce6000-a8c2-11ea-8bbd-c3361d0d5540.png)
![3](https://user-images.githubusercontent.com/52768739/83961110-a4c95080-a8c2-11ea-8e8d-afb3adc5d5d0.png)

**Comment by linzefan0612** [comment]
> ```js
>  let title = location.pathname.substr(0, 50);
>  let gitalk = new Gitalk({
>       clientID: "生成的clientID",
>       clientSecret: "生成的clientSecret",
>       repo: "blog", // 仓库名
>       owner: "linzefan0612",
>       admin: ["linzefan0612"],
>       id: title,
>       distractionFreeMode: false
>     });
> ```
> 
> ![1](https://user-images.githubusercontent.com/52768739/83961106-967b3480-a8c2-11ea-8a95-f28fdc87b227.png)
> ![2](https://user-images.githubusercontent.com/52768739/83961109-a1ce6000-a8c2-11ea-8bbd-c3361d0d5540.png)
> ![3](https://user-images.githubusercontent.com/52768739/83961110-a4c95080-a8c2-11ea-8e8d-afb3adc5d5d0.png)

**Comment by OliverLew** [comment]
我看了你的主页，那个仓库名不是`blogs`吗？没有`blog`这个仓库

**Comment by linzefan0612** [comment]
> 我看了你的主页，那个仓库名不是`blogs`吗？没有`blog`这个仓库

是的- -，就是我这个仓库名错乱导致的，后面我改好了，谢谢啦
