### ISSUE TITLE
跨域问题有人出现过吗？

### ISSUE THREAD

**Issue by w0nwig** [gitalk/gitalk#392]
![image](https://user-images.githubusercontent.com/22488212/86592573-5349d980-bfc6-11ea-8a7d-38aa01bd35e8.png)

**Comment by liuyib** [comment]
@w0nwig 我的也一直出现跨域问题

**Comment by w0nwig** [comment]
![image](https://user-images.githubusercontent.com/22488212/86601717-3f0cd900-bfd4-11ea-9837-8499aaef06fd.png)
一直在这转着～～～

**Comment by booxood** [comment]
因为网络请求 `https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token` 失败了，大概率是因为beiqiang 了。

**Comment by yanshenxian** [comment]
@booxood  不对 我看网络请求根本就没有请求 cors-anywhere 域名
![image](https://user-images.githubusercontent.com/58985624/89704687-b2fe2080-d988-11ea-8107-11ee0e2f10e5.png)

**Comment by yanshenxian** [comment]
> @booxood 不对 我看网络请求根本就没有请求 cors-anywhere 域名
> ![image](https://user-images.githubusercontent.com/58985624/89704687-b2fe2080-d988-11ea-8107-11ee0e2f10e5.png)

提了个 pr，通过反向代理的方式解决github api请求不通的问题
https://github.com/gitalk/gitalk/pull/401

**Comment by RamboQiu** [comment]
哭，求解，碰到相同的问题
VM15:1 Access to XMLHttpRequest at 'https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token' from origin 'https://gitalk.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by RamboQiu** [comment]
> 哭，求解，碰到相同的问题
> VM15:1 Access to XMLHttpRequest at 'https://cors-anywhere.herokuapp.com/https://github.com/login/oauth/access_token' from origin 'https://gitalk.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

额，今天又恢复了https://cors-anywhere.herokuapp.com/不够稳定

**Comment by Taoey** [comment]
我是授权之后报403异常，应该是统一个问题
![image](https://user-images.githubusercontent.com/22273652/107201166-9758fd00-6a33-11eb-901b-239f13d9fbec.png)

**Comment by Germey** [comment]
同，见 https://cuiqingcai.com/message/

**Comment by booxood** [comment]
更新版本到 1.7.2 或者修改配置增加 `proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'`
