### ISSUE TITLE
未找到相關的 Issues

### ISSUE THREAD

**Issue by steveyiyo** [gitalk/gitalk#394]
你好，我使用Hexo 的 tranquilpeak主題
但我設定好gitalk後，他一直報錯"未找到相關的 Issues"，請問這個問題要如何解決
謝謝

https://diary.yiy.tw/hello/

![Annotation 2020-07-15 014946](https://user-images.githubusercontent.com/43361940/87459082-7d8e3d80-c63d-11ea-8f3f-ad5e7711cca0.png)

**Comment by deniapps** [comment]
I think you forgot to add 'admin' in your gitalk option. 

> admin Array
> Required. GitHub repository owner and collaborators. (Users having write access to this repository)

Something like,
`admin: ['steveyiyo']`

Also, you should add quotes around String, like
```
owner: "Yi-Diary"
repo: "Comments" //I believe this is case sensitive.
```
After that you need to click 'Login with Github" on your page: https://diary.yiy.tw/hello/ to log in with 'steveyiyo'.

Reference: https://deniapps.com/blog/chose-gitalk-for-comment-system

**Comment by steveyiyo** [comment]
Thanks for help!
