### ISSUE TITLE
关于回复评论的建议

### ISSUE THREAD

**Issue by Draveness** [gitalk/gitalk#40]
能不能将回复做到评论的下面，否则如果评论很多的话，回复和原问题都连不到一块，很难找

另外这是一个非常好的 repo，谢谢 👍

**Comment by tiexo** [comment]
这个建议是好的，估计有难度？
issue默认就是盖楼模式

**Comment by Draveness** [comment]
@tiexo 是的，我看了一下每一个 issue 都带一个 databaseId 字段，是不是可以在展示时解析 body 中的内容，建立父子关系，比如：

```ruby
reply: 32321313
@xxxx
----
回复 xxx 的评论
```

我不太熟悉前端和 React，尝试着看了一下，发现实在是看不明白。。

**Comment by tiexo** [comment]
@Draveness 等 @booxood 评估下。

**Comment by Draveness** [comment]
好的

**Comment by booxood** [comment]
@Draveness 在回复的内容前面增加一个 `标识` 来表示是回复的哪一个评论，理论上是可以的。

但就像 @tiexo 说的 `issue默认就是盖楼模式`，所以

- 分页加载评论的时候还是按时间排序来加载的，那后面的那些 `回复` 还是需要一直往后加载才能展示
- 在加载的过程中，你也不太好知道加载了那些 `回复`
- 如果你需要查看某个评论的所有回复，你需要先把所有的评论都加载完，然后再回头去看那个评论的回复

当然，这样实现之后回复展示的结构看起来比较清晰，但如果嵌套太多，变成 `金字塔`那样也不好看。

另外，我觉得那样展示更像是在聊天，评论和聊天还是有些差别的。

所以，这个功能暂时不考虑吧。

**Comment by tiexo** [comment]
@booxood 正巧我还有个问题，关于评论排序的。
我发现配置里面可以调整评论按时间倒序，正序排列，但是仅限于登录后才生效。

未登录状态，只能按照创建时间正序排列，这个能修改么？

**Comment by Draveness** [comment]
@booxood 好的，谢谢

**Comment by booxood** [comment]
@tiexo 未登录时修改不了。Github 的 Graphql  API 才支持按时间排序，但需要登录才能调用 Graphql  的
 API。

**Comment by ehlxr** [comment]
@booxood 回复的的时候，能不能不让修改被回复的内容了？一修改很容易更变回复的样式
![image](https://user-images.githubusercontent.com/11313370/32765180-4ffff7f8-c944-11e7-809c-939cd57efd5d.png)

**Comment by booxood** [comment]
@ehlxr 都属于回复的内容，不让修改不太好吧。修改更自由点，可以对想回复的内容进行删减编辑。
