### ISSUE TITLE
已有评论包含图片的话，输入的时候会不停卡顿

### ISSUE THREAD

**Issue by Draveness** [gitalk/gitalk#42]
https://gitalk.github.io 这里最下面由一个不是特别大的表情，也会重绘

可能因为输入的过程中会不断重绘 div，然后过长的图片会不停的被重新绘制，所以下面一直在跳？

**Comment by Draveness** [comment]
![out](https://user-images.githubusercontent.com/6493255/32131365-f1fe2ef8-bbde-11e7-9de7-53cf6d6b67ee.gif)

**Comment by booxood** [comment]
在 Mac Chrome 61.0.3163.100（正式版本）上，没有重现这个问题。。

**Comment by Draveness** [comment]
难道是 safari 的问题？

**Comment by booxood** [comment]
也没重现。。

**Comment by Draveness** [comment]
@booxood  我在 Chrome 上的这个链接 https://draveness.me/git-comments-initialize 试了也没有这个问题，但是在 safari 上就有

**Comment by Draveness** [comment]
![out](https://user-images.githubusercontent.com/6493255/32140188-4d23cf0a-bc92-11e7-9190-4fe9f62bd9ee.gif)

**Comment by booxood** [comment]
无法重现。暂时先关闭 issue。
