### ISSUE TITLE
gitalk can NOT work without cors-anywhere

### ISSUE THREAD

**Issue by ShuYuMo2003** [gitalk/gitalk#425]
https://github.com/Rob--W/cors-anywhere/issues/301

gitalk can NOT work without cors-anywhere. Is there any way to fix it?

**Comment by andrewchoongwonlee** [comment]
Need help on this problem as well

**Comment by andrewchoongwonlee** [comment]
Forked [https://github.com/Rob--W/cors-anywhere](https://github.com/Rob--W/cors-anywhere) repo to host proxy on my own. 
Changed the proxy url and got it fixed

**Comment by Germey** [comment]
solution: https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ

**Comment by ShuYuMo2003** [comment]
> solution: https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ

https://github.com/Zibri/cloudflare-cors-anywhere

> To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.

不是很懂为什么一句话能解决的事情需要写一篇若干k的文章解决问题。

**Comment by ShuYuMo2003** [comment]
> solution: https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ

当然，谢谢你的热心。

**Comment by xiaochunjimmy** [comment]
@Germey 感谢老哥的文章，让我清晰认知到了这个问题出现的原因以及解决问题的长久之计，写得很详细，方案也很好，不用去修改 js 源码，文章很棒！

**Comment by tubone24** [comment]
It will be a work-around, but if you are running on a platform that has a backend API such as Netlify or Vercel, you can create a backend and change the proxy as follows. I hope this is helpful.

API `functions/src/cors-proxy-github.js`

```javascript
const axios = require('axios')

exports.handler = (event, context) => {
  const body = JSON.parse(event.body);
  const headers = {
    accept: 'application/json',
  };
  return axios.post('https://github.com/login/oauth/access_token', body, {headers: headers}).then((response) => {
    return {
      statusCode: 200,
      body: JSON.stringify({access_token: response.data.access_token, token_type: response.data.token_type, scope: response.data.scope}),
    };
  }).catch((error) => {
    return {
      statusCode: 500,
      body: JSON.stringify({error: error})
    }
  })
};
```

`gitalk.jsx`

```javascript
  constructor (props) {
    super(props)
    this.options = Object.assign({}, {
      id: window.location.href,
      number: -1,
      labels: ['Gitalk'],
      title: window.document.title,
      body: '', // window.location.href + header.meta[description]
      perPage: 10,
      createIssueManually: false,
      proxy: 'https://blog.tubone-project24.xyz/.netlify/functions/cors-proxy-github',
      flipMoveOptions: {
        staggerDelayBy: 150,
        appearAnimation: 'accordionVertical',
        enterAnimation: 'accordionVertical',
        leaveAnimation: 'accordionVertical',
      },
      enableHotKey: true,

```

**Comment by ShuYuMo2003** [comment]
@tubone24 
Thank you for you suggestion!! 
I set up a worker on cloudflare to be my proxy. And my gitalk installed on my blog is working now.

https://github.com/Zibri/cloudflare-cors-anywhere

**Comment by booxood** [comment]
更新版本到 1.7.2 或者修改配置增加 `proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'`

需要动手的同学也可以参考楼上 @tubone24 @ShuYuMo2003 提供的方法自己搭建。
