### ISSUE TITLE
Request failed with status code 403

### ISSUE THREAD

**Issue by Justice-love** [gitalk/gitalk#426]
#### Gitalk 版本
    <link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
    <script src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
    最新版本
#### 报错信息？
Error: Request failed with status code 403
#### 浏览器版本？
safari
#### 复现步骤？
github网页，gitalk登出，然后gitalk登陆

![1](https://user-images.githubusercontent.com/3375778/107166144-0f9dcf00-69f0-11eb-89d3-94adea00a7ce.png)

**Comment by Justice-love** [comment]
通过 https://github.com/Rob--W/cors-anywhere 自建了一个代理服务器， 
默认的已被限制 https://github.com/Rob--W/cors-anywhere/issues/301

**Comment by NoordZeedebuTirpitz** [comment]
您好，请问能详细说明一下怎么解决的么，我也遇到了这个问题

**Comment by Justice-love** [comment]
> 您好，请问能详细说明一下怎么解决的么，我也遇到了这个问题

用这个部署一下https://github.com/Rob--W/cors-anywhere，node server.js启动就行 https://github.com/Rob--W/cors-anywhere#demo-server
这里是使用demo https://github.com/Rob--W/cors-anywhere#example

**Comment by booxood** [comment]
更新版本到 1.7.2 或者修改配置增加 `proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'`

**Comment by Hanpeng-Chen** [comment]
> 您好，请问能详细说明一下怎么解决的么，我也遇到了这个问题

我是在Cloud Flare上创建一个worker搭建的在线代理，只要将JS脚本复制到CloudFlare的worker的脚本编辑器中，保存部署就可以了，操作起来比较简单。
脚本：https://github.com/Zibri/cloudflare-cors-anywhere
有兴趣的可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/

**Comment by jinbaotang** [comment]
> > 您好，请问能详细说明一下怎么解决的么，我也遇到了这个问题
> 
> 我是在Cloud Flare上创建一个worker搭建的在线代理，只要将JS脚本复制到CloudFlare的worker的脚本编辑器中，保存部署就可以了，操作起来比较简单。
> 脚本：https://github.com/Zibri/cloudflare-cors-anywhere
> 有兴趣的可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/

您好，不是很明白，只要将JS脚本复制到CloudFlare的worker的脚本编辑器中，这句话是啥意思啊

**Comment by Hanpeng-Chen** [comment]
> > > 您好，请问能详细说明一下怎么解决的么，我也遇到了这个问题
> > 
> > 
> > 我是在Cloud Flare上创建一个worker搭建的在线代理，只要将JS脚本复制到CloudFlare的worker的脚本编辑器中，保存部署就可以了，操作起来比较简单。
> > 脚本：https://github.com/Zibri/cloudflare-cors-anywhere
> > 有兴趣的可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/
> 
> 您好，不是很明白，只要将JS脚本复制到CloudFlare的worker的脚本编辑器中，这句话是啥意思啊

@jinbaotang 把 https://github.com/Zibri/cloudflare-cors-anywhere/blob/master/index.js 这里的代码复制你在Cloud Flare创建的worker的脚本编辑器中，点击保存并部署即可
![image](https://user-images.githubusercontent.com/20657777/117227392-4ba6cb80-ae49-11eb-87bb-e3fea67c8341.png)
