### ISSUE TITLE
在授权gitalk后出现403错误

### ISSUE THREAD

**Issue by White-NX** [gitalk/gitalk#429]
#### Gitalk 版本

v 1.7.0

#### 报错信息？

Error: Request failed with status code 403

#### 浏览器版本？

Via浏览器，最新版本

#### 复现步骤？

按照README文件里的教程写了js：

```html
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
  <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>
  <script>
var gitalk = new Gitalk({
  clientID: '24d****',
  clientSecret: 'c29****',
  repo: 'gitalk',
  owner: 'White-NX',
  admin: ['White-NX'],
  id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: true  // Facebook-like distraction free mode
})

gitalk.render('gitalk-container')
</script>
<div id="gitalk-container"></div>
```
授权后报错，403

我的网站：<https://java.eyling.top> 这也是报错的位置。

**Comment by tuoxiao** [comment]
此问题同现，等大佬解决。

**Comment by GeekXwb** [comment]
我也有这个问题，官方的demo也是403 问题应该不在我们

**Comment by PinkHello** [comment]
同样的情况

**Comment by wtnyzhsq** [comment]
The same problem

**Comment by OliverLew** [comment]
这个和 #425 #428 是同样的问题

**Comment by Germey** [comment]
Same

**Comment by escapar** [comment]
You should deploy your own instance of the CORS proxy service 

https://stackoverflow.com/questions/47076743/cors-anywhere-herokuapp-com-not-working-503-what-else-can-i-try

**Comment by Goopher97** [comment]
有这个问题的朋友可以尝试访问一下https://cors-anywhere.herokuapp.com/corsdemo这个网站，然后点击![](https://gitee.com/goopher998/tuchuang/raw/master/img/QQ%E6%88%AA%E5%9B%BE20210212161442.png) 然后返回![](https://gitee.com/goopher998/tuchuang/raw/master/img/QQ%E6%88%AA%E5%9B%BE20210212161534.png) 就可以正常使用了

**Comment by OliverLew** [comment]
@Goopher97 那个是开发者为了降低访问量、提醒不要滥用（因为它仅仅是个demo）设置的“门槛”，不能作为解决方案。最好就是楼上说的，gitalk这边或者使用gitalk的自己clone过来搭建代理服务。

**Comment by Goopher97** [comment]
> @Goopher97 那个是开发者为了降低访问量、提醒不要滥用（因为它仅仅是个demo）设置的“门槛”，不能作为解决方案。最好就是楼上说的，gitalk这边或者使用gitalk的自己clone过来搭建代理服务。

确实自己搞比较好……不过我懒![image](https://user-images.githubusercontent.com/37131466/107746097-43f6ef80-6d50-11eb-85c5-fb8c12c2cafe.jpeg)

**Comment by Goopher97** [comment]
> @Goopher97 那个是开发者为了降低访问量、提醒不要滥用（因为它仅仅是个demo）设置的“门槛”，不能作为解决方案。最好就是楼上说的，gitalk这边或者使用gitalk的自己clone过来搭建代理服务。

这玩意懒不得了哎，换台设备又不行了![image](https://user-images.githubusercontent.com/37131466/107751317-36ddfe80-6d58-11eb-9100-23f67bc5130a.jpeg)

**Comment by Goopher97** [comment]
这次直接去嫖了一个CORS proxy,把gitalk.js的6794行改为proxy: 'https://netnr-proxy.cloudno.de/https://github.com/login/oauth/access_token',就可以了。具体能用多久我也没普，且用且珍惜。 ![](https://gitee.com/goopher998/tuchuang/raw/master/img/9a67d24560cc888ed61ff8c6dbcc3823.GIF)

**Comment by Germey** [comment]
@Goopher97 哪里嫖的

**Comment by Goopher97** [comment]
> @Goopher97 哪里嫖的

Gitee上看到的……创建了有两年了

**Comment by Germey** [comment]
感谢，写到博客了 https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ

**Comment by GeekXwb** [comment]
我是在使用docsify的时候发现的，
感谢楼上提供思路
我已经在next仓库提交了pull request
分享一下我搭建的代理地址：

https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

**Comment by Goopher97** [comment]
> 我是在使用docsify的时候发现的，
> 感谢楼上提供思路
> 我已经在next仓库提交了pull request
> 分享一下我搭建的代理地址：
> 
> https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token
> 
> 

感谢老哥，下次挂了换你这个用用![image](https://user-images.githubusercontent.com/37131466/107794128-06b35180-6d92-11eb-974c-2a23d8a1c77f.jpeg)

**Comment by ShuYuMo2003** [comment]
https://github.com/Zibri/cloudflare-cors-anywhere

>To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.

不是很懂为什么要嫖… 部署一下真的很简单…

**Comment by Goopher97** [comment]
> https://github.com/Zibri/cloudflare-cors-anywhere
> 
> 
> 
> >To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> 
> 
> 
> 不是很懂为什么要嫖… 部署一下真的很简单…

![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……

**Comment by lyc8503** [comment]
遇到同样问题.

**Comment by 98wb** [comment]
问题相同

Error: Request failed with status code 403

**Comment by 98wb** [comment]
> 我是在使用docsify的时候发现的，
> 感谢楼上提供思路
> 我已经在next仓库提交了pull request
> 分享一下我搭建的代理地址：
> 
> https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

白嫖了老哥的代理，感谢老哥。

**Comment by ShuYuMo2003** [comment]
> > https://github.com/Zibri/cloudflare-cors-anywhere
> > > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> > 
> > 
> > 不是很懂为什么要嫖… 部署一下真的很简单…
> 
> ![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……

哥哥您试一下就知道了吧…您那张截图的最下面已经能看到 `worker` 了，您点开稍微看一下就会了吧，那个库里的代码已经适配了 worker 的格式了，直接粘进去就好了

**Comment by Goopher97** [comment]
> > > https://github.com/Zibri/cloudflare-cors-anywhere
> 
> > > > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> 
> > > 
> 
> > > 
> 
> > > 不是很懂为什么要嫖… 部署一下真的很简单…
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……
> 
> 
> 
> 哥哥您试一下就知道了吧…您那张截图的最下面已经能看到 `worker` 了，您点开稍微看一下就会了吧，那个库里的代码已经适配了 worker 的格式了，直接粘进去就好了

我自己弄的登录gitalk时错误Error: no access token……哎

**Comment by Goopher97** [comment]
> > > > https://github.com/Zibri/cloudflare-cors-anywhere
> > 
> > > > > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> > 
> > > > 
> > 
> > > > 
> > 
> > > > 不是很懂为什么要嫖… 部署一下真的很简单…
> > 
> > > 
> > 
> > > ![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……
> > 
> > 
> > 
> > 哥哥您试一下就知道了吧…您那张截图的最下面已经能看到 `worker` 了，您点开稍微看一下就会了吧，那个库里的代码已经适配了 worker 的格式了，直接粘进去就好了
> 
> 我自己弄的登录gitalk时错误Error: no access token……哎
> 

https://sweet-waterfall-ced4.1520396767.workers.dev/

**Comment by Goopher97** [comment]
……原来是忘记问号了，我就说我自己搞得怎么都用不了。 https://sweet-waterfall-ced4.1520396767.workers.dev/?https://github.com/login/oauth/access_token 有需要的兄弟可以拿去用。

**Comment by Heat-Wade** [comment]
> 
> 
> https://github.com/Zibri/cloudflare-cors-anywhere
> 
> > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> 
> 不是很懂为什么要嫖… 部署一下真的很简单…

请问clone源码后npm install后是把整个文件夹上传到heroku还是只把install生成的那个node_modules上传？

> 
> 
> https://github.com/Zibri/cloudflare-cors-anywhere
> 
> > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> 
> 不是很懂为什么要嫖… 部署一下真的很简单…

请问clone源码后npm install后是把整个文件夹上传到heroku还是只把install生成的那个node_modules上传？

**Comment by Coder-Liuu** [comment]
> 这次直接去嫖了一个CORS proxy,把gitalk.js的6794行改为 proxy: 'https://netnr-proxy.cloudno.de/https://github.com/login/oauth/access_token', 就可以了。具体能用多久我也没普，且用且珍惜。 ![](https://camo.githubusercontent.com/1ec07ea66ea09f1d5b790b66bf97c8771f7d1a6552c8312e15647e3b9c2c6351/68747470733a2f2f67697465652e636f6d2f676f6f706865723939382f7475636875616e672f7261772f6d61737465722f696d672f39613637643234353630636338383865643631666638633664626363333832332e474946)


白嫖了老哥的代理，感谢老哥。

**Comment by Ruanxingzhi** [comment]
> @Goopher97
> 感谢，写到博客了 https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ

抱歉，这篇博客无法访问。2021/02/24

**Comment by booxood** [comment]
更新版本到 1.7.2 或者修改配置增加 `proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'`

很多同学提供了搭建的方式，也可以自己动手搭建代理：
https://github.com/gitalk/gitalk/issues/425#issuecomment-782853622
https://github.com/gitalk/gitalk/issues/425#issuecomment-782858102
https://github.com/gitalk/gitalk/issues/429#issuecomment-778288475

**Comment by internelp** [comment]
可以使用 nginx 简单配置搭建一个自己使用的反向代理：
https://www.qiansw.com/solve-the-problem-of-using-gitalk-authorization-403.html

**Comment by Germey** [comment]
> > @Goopher97
> > 感谢，写到博客了 https://mp.weixin.qq.com/s/Lwl9rf95EqlTYLfconjflQ
> 
> 抱歉，这篇博客无法访问。2021/02/24

@Ruanxingzhi 

https://cuiqingcai.com/30010.html

**Comment by Goopher97** [comment]
> > > https://github.com/Zibri/cloudflare-cors-anywhere
> > > > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> > > 
> > > 
> > > 不是很懂为什么要嫖… 部署一下真的很简单…
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……
> 
> 哥哥您试一下就知道了吧…您那张截图的最下面已经能看到 `worker` 了，您点开稍微看一下就会了吧，那个库里的代码已经适配了 worker 的格式了，直接粘进去就好了

真的好难，自己的弄了好久都是用不了 哎
https://cloudflare-cors-anywhere.1520396767.workers.dev/

**Comment by Hanpeng-Chen** [comment]
@Goopher97 你是不是链接地址弄错了？我自己搭建了一个是没问题的
具体搭建过程可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/

**Comment by Hanpeng-Chen** [comment]
> > > > https://github.com/Zibri/cloudflare-cors-anywhere
> > > > > To create your own is very easy, you just need to set up a cloudflare account and upload the worker code.
> > > > 
> > > > 
> > > > 不是很懂为什么要嫖… 部署一下真的很简单…
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/37131466/107865434-3a30d180-6ea1-11eb-93ec-2a28e180c8c3.png) 没有域名可以创建Cloudflare worker么……
> > 
> > 
> > 哥哥您试一下就知道了吧…您那张截图的最下面已经能看到 `worker` 了，您点开稍微看一下就会了吧，那个库里的代码已经适配了 worker 的格式了，直接粘进去就好了
> 
> 真的好难，自己的弄了好久都是用不了 哎
> https://cloudflare-cors-anywhere.1520396767.workers.dev/

@Goopher97 你是不是链接地址弄错了？我自己搭建了一个是没问题的
具体搭建过程可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/

**Comment by wsmbsbbz** [comment]
> 我是在使用docsify的时候发现的，
> 感谢楼上提供思路
> 我已经在next仓库提交了pull request
> 分享一下我搭建的代理地址：
> 
> https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

感谢老哥，已经用上了👍

**Comment by z974890869** [comment]
> 我是在使用docsify的时候发现的，
> 感谢楼上提供思路
> 我已经在next仓库提交了pull request
> 分享一下我搭建的代理地址：
> 
> https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

用上了，感谢

**Comment by gsgs-libin** [comment]
> 我是在使用docsify的时候发现的，
> 感谢楼上提供思路
> 我已经在next仓库提交了pull request
> 分享一下我搭建的代理地址：
> 
> https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token

白嫖了老哥的，谢谢

**Comment by tiax615** [comment]
> > 我是在使用docsify的时候发现的，
> > 感谢楼上提供思路
> > 我已经在next仓库提交了pull request
> > 分享一下我搭建的代理地址：
> > https://shielded-brushlands-08810.herokuapp.com/https://github.com/login/oauth/access_token
> 
> 白嫖了老哥的，谢谢

白嫖了老哥的，谢谢
