### ISSUE TITLE
希望支持 Gitee

### ISSUE THREAD

**Issue by tomcup** [gitalk/gitalk#430]
#### Gitalk 版本
All
#### 报错信息？
None
#### 浏览器版本？
-
#### 复现步骤？
-

既然支持 Github，支持 Gitee 也差不多吧。

**Comment by fnsflm** [comment]
理由呢?
有gitee账号的大概都会有github账号吧? 评论区也不用太担心国内github访问速度慢的问题吧?
还是有其它的考虑?

**Comment by windmemory** [comment]
@fnsflm 

最近貌似github的访问越来越差了，甚至好多时候本地的push和pull都不行。我尝试把一些希望面向国内开发者群体的内容搬运到gitee上，所以希望能在gitee上实现全家桶。最近在搭hexo的博客，想用gitalk来实现hexo里面的评论系统，所以不知道能否支持一下gitee的接口。

国内的小伙伴，能把github玩的6的我感觉没有很多，凭感觉说可能不到50%，所以如果咱们这个gitalk能够支持gitee的话，就可以很方便的让国内的小伙伴也都自己搭一搭了。如果能支持，我愿意contribute一下gitalk配置gitee的相关文档

**Comment by StrayCamel247** [comment]
没必要强求gitalk支持github，最近访问比较慢是因为管制原因，博客园也停了几天。

**Comment by windmemory** [comment]
> 没必要强求gitalk支持github，最近访问比较慢是因为管制原因，博客园也停了几天。

当然，没有必要**强求**任何开源项目做任何feature。我只是从个人角度反馈下有这个需求，并且如果能支持这个需求的话，我本人愿意也同样contribute一部分。

**Comment by willin** [comment]
> > 没必要强求gitalk支持github，最近访问比较慢是因为管制原因，博客园也停了几天。
> 
> 当然，没有必要**强求**任何开源项目做任何feature。我只是从个人角度反馈下有这个需求，并且如果能支持这个需求的话，我本人愿意也同样contribute一部分。

fork and implement it by yourself.

**Comment by tonyqus** [comment]
这问题是不是可以关了，gitee开issue弄不好也要审核了，中国特色伪开源平台！

**Comment by deskside** [comment]
> 这问题是不是可以关了，gitee开issue弄不好也要审核了，中国特色伪开源平台！

太真实了……我之前试着用Gitee部署博客，一些非常正常的博客内容都被审核不通过，我一整个大无语，最后还是用回Github。我只能说不会翻墙的人就别看我的博客了……毕竟会翻墙真的是基本操作，哎

**Comment by tomcup** [comment]
不用翻墙, Q个DNS就可以了,比如OpenDNS。

Tomcup
________________________________

**Comment by tomcup** [comment]
这几年經历让人深刻理解到了Gitee的不可用性
