### ISSUE TITLE
gitalk授权登录后报错403

### ISSUE THREAD

**Issue by NuyoaH-L** [gitalk/gitalk#433]

**Comment by booxood** [comment]
更新版本到 1.7.2 或者修改配置增加 `proxy: 'https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token'`

**Comment by hei-lou** [comment]
配置了之后仍然显示403
![image](https://user-images.githubusercontent.com/8412922/111896187-9bc0fe80-8a52-11eb-8929-21a41fa1376d.png)

**Comment by booxood** [comment]
> 配置了之后仍然显示403
> ![image](https://user-images.githubusercontent.com/8412922/111896187-9bc0fe80-8a52-11eb-8929-21a41fa1376d.png)

@hei-lou 配置没生效。截图里的请求还是旧的，不是配置的。

也可以升级版本吧。

**Comment by hei-lou** [comment]
已解决 感谢

**Comment by 6-6** [comment]
还好搜到您的答案，感谢！

**Comment by Hanpeng-Chen** [comment]
可以自己在Cloud Flare上搭建一个在线代理，这样就不用担心别人分享的代理地址不能用了。
搭建过程可以参考：https://www.chenhanpeng.com/create-own-cors-anywhere-to-resolve-the-request-with-403/
