### ISSUE TITLE
[求助] Error: Request failed with status code 405

### ISSUE THREAD

**Issue by KarlunLai-void** [gitalk/gitalk#437]
請求大佬幫忙...拜託了！
我被這問題困擾很久了，這幾天一直解決不掉

#### Gitalk 版本
1.7.2

#### 报错信息？
Error: Request failed with status code 405
![image](https://user-images.githubusercontent.com/40635383/111011601-ea2c2880-83d4-11eb-9579-b1d9a4f38c8c.png)

#### 浏览器版本？
Google Chrome
Version 89.0.4389.82 (Official Build) (64-bit)

#### 复现步骤？
使用Hexo+NexT主題
![image](https://user-images.githubusercontent.com/40635383/111011680-22336b80-83d5-11eb-8d8e-1659317835af.png)

![image](https://user-images.githubusercontent.com/40635383/111011719-3e370d00-83d5-11eb-9342-8a02d2c9fcd3.png)

**Comment by KarlunLai-void** [comment]
找到錯誤了，謝謝...

hexo的NexT主題內
layout/_third-party/comments/gitalk.swig
檔案設置錯誤了，忘記上個月設置時有用到proxy。這次把它拿掉就正常了

I found the error, thx...
hexo/themes/NexT/layout/_third-party/comments/gitalk.swig
The file setting is wrong.
I used the proxy a month ago, I forgot it.
And it execute normally when I remove this line.

```
{%- if page.comments %}
{%- set gitalk_css_uri = theme.vendors.gitalk_css or '//cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.css' %}
<link rel="stylesheet" href="{{ gitalk_css_uri }}">

{%- set gitalk_js_uri = theme.vendors.gitalk_js or '//cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js' %}

<script>
NexT.utils.loadComments(document.querySelector('#gitalk-container'), () => {
  NexT.utils.getScript('{{ gitalk_js_uri }}', () => {
    var gitalk = new Gitalk({
      clientID    : '{{ theme.gitalk.client_id }}',
      clientSecret: '{{ theme.gitalk.client_secret }}',
      repo        : '{{ theme.gitalk.repo }}',
      owner       : '{{ theme.gitalk.github_id }}',
      admin       : ['{{ theme.gitalk.admin_user }}'],
      id          : '{{ gitalk_md5(page.path) }}',
      proxy       : '{{ theme.gitalk.proxy }}', // <-- remove this line
      {%- if theme.gitalk.language == '' %}
        language: window.navigator.language || window.navigator.userLanguage,
      {% else %}
        language: '{{ theme.gitalk.language }}',
      {%- endif %}
      distractionFreeMode: {{ theme.gitalk.distraction_free_mode }}
    });
    gitalk.render('gitalk-container');
  }, window.Gitalk);
});
</script>
{%- endif %}
```

**Comment by Promin3** [comment]
遇到了同样的问题...
