### ISSUE TITLE
Question about the id contained in labels

### ISSUE THREAD

**Issue by Oscaner** [gitalk/gitalk#438]
Can we create an option to allow user contain ID in labels or not contain ? 

Because sometimes we want to use MD5 ID, it's not readable.

https://github.com/gitalk/gitalk/blob/4f4024bf7f30ea340b41cce2b4ef85b1f42830a7/src/gitalk.jsx#L276

**Comment by booxood** [comment]
`id` is uniquely associated with issue. If without `id`, the association cannot be determined.
