### ISSUE TITLE
好像gitalk的css有些问题,评论框获得焦点之后会闪并且会产生一个遮罩

### ISSUE THREAD

**Issue by xiaomoinfo** [gitalk/gitalk#44]
https://blog.xiaomo.info/2017/GameServerType/

**Comment by booxood** [comment]
`无干扰模式（设置 distractionFreeMode 为 true 开启）`

不喜欢就设置为 `false` 关闭吧

**Comment by xiaomoinfo** [comment]
@booxood 好的，己经解决问题。 多谢作者开发出这么好用的评论插件
