### ISSUE TITLE
为什么作者浏览 也会在github 绑定的仓库 创建 issues？

### ISSUE THREAD

**Issue by aaaaaajie** [gitalk/gitalk#440]
作者只是浏览了一下并没有评论 就会开一个 issues 到 github comment，而其他人不会，希望不会推送浏览记录

![image](https://user-images.githubusercontent.com/36189354/111934267-0d08bc00-8afc-11eb-9b78-b28b970d2faf.png)

![image](https://user-images.githubusercontent.com/36189354/111934092-b8654100-8afb-11eb-9864-c7ef2db97d72.png)

**Comment by C0MM4ND** [comment]
https://github.com/gitalk/gitalk/blob/4f4024bf7f30ea340b41cce2b4ef85b1f42830a7/src/gitalk.jsx#L61

默认情况下会自动创建issue，不需要的话就在配置里把createIssueManually设为true

**Comment by aaaaaajie** [comment]
> https://github.com/gitalk/gitalk/blob/4f4024bf7f30ea340b41cce2b4ef85b1f42830a7/src/gitalk.jsx#L61
> 
> 默认情况下会自动创建issue，不需要的话就在配置里把createIssueManually设为true

非常感谢 🙏，hexo 不支持 createIssueManually 这个参数，我 修改了 hexo themes 主题 下的 gitalk.swing，支持了 用户 设置 其状态！```js createIssueManually: {{ theme.gitalk.create_issue_manually }} ```
