### ISSUE TITLE
secret key泄露

### ISSUE THREAD

**Issue by Throokie** [gitalk/gitalk#444]
#### 报错信息？
无
#### 复现步骤？
查看部署有该产品的源码

![image](https://user-images.githubusercontent.com/58783886/113593452-097f4400-9669-11eb-81df-10149720d1a1.png)

**Comment by a08381** [comment]
[暴露 clientSecret 是否安全](https://github.com/gitalk/gitalk/wiki/Q&A#%E6%9A%B4%E9%9C%B2-clientsecret-%E6%98%AF%E5%90%A6%E5%AE%89%E5%85%A8)

**Comment by booxood** [comment]
同楼上
