### ISSUE TITLE
关于权限要求的疑问

### ISSUE THREAD

**Issue by jhdxr** [gitalk/gitalk#447]
#### Gitalk 版本
N.A.

#### 报错信息？
使用github登录时提示索要对于所有公开库的写权限，这个是否是必要的？
```
This application will be able to read and write all public repository data. This includes the following:
```

#### 浏览器版本？
N.A.

#### 复现步骤？
1. 打开演示站点 https://gitalk.github.io/
2. 点击 使用github登录
3. 检查Repositories下的具体说明

**Comment by booxood** [comment]
同 https://github.com/gitalk/gitalk/issues/95
