### ISSUE TITLE
issue重复

### ISSUE THREAD

**Issue by evilchurch** [gitalk/gitalk#45]
每点击(刷新)文章页面一次，就会新建一个issue，结果就是相同的文章会有很多issue

**Comment by booxood** [comment]
新建的 issue 的 `label` 是一样的吗？

**Comment by evilchurch** [comment]
@booxood 一样的，[evilchurch.github.io](https://github.com/evilchurch/evilchurch.github.io/issues?q=is:issue+is:closed)可以看一下我关掉的issue

**Comment by booxood** [comment]
@evilchurch 你打开一个 issue 试下

**Comment by evilchurch** [comment]
@booxood 你看一眼，刷新一下就会重新开issue

**Comment by booxood** [comment]
@evilchurch  现在再刷新呢？ 应该不会了吧？

**Comment by evilchurch** [comment]
@booxood 之前点开的那篇文章不会了，但是其他的文章还是会重复开

**Comment by evilchurch** [comment]
@booxood 配置里id设置为了location.pathname，想不通是什么原因

**Comment by booxood** [comment]
@evilchurch 你这个很奇怪。。已经有了。。还创建。。

你刷新页面的时候留意下 `https://api.github.com/repos/evilchurch/evilchurch.github.io/issues?...` 这个请求，看看返回数据组是里空的还是有数据的，这个请求就是获取 issue 的。

另外，可以先设置 `createIssueManually ` 为 `true`，改成手工创建 issue 来规避这个问题。

**Comment by evilchurch** [comment]
抓包看了一下，返回的是有数据的，实在不行就试试手动创建吧，谢谢啦
![image](https://user-images.githubusercontent.com/18813780/32310174-9cf2afb4-bf5e-11e7-9af4-086dc33a03e5.png)
