### ISSUE TITLE
反代好像又崩了

### ISSUE THREAD

**Issue by 24kcsplus** [gitalk/gitalk#456]
#### Gitalk 版本
1.7.3
#### 报错信息？
Error: Network Error

看样子是反代又崩了
![image](https://user-images.githubusercontent.com/60341267/121811449-08851700-cc97-11eb-867e-12a67e14475b.png)

**Comment by 24kcsplus** [comment]
好像不是反代的问题，好像是被墙了（明明主站可以访问）
![image](https://user-images.githubusercontent.com/60341267/121811719-ce684500-cc97-11eb-882e-5cad3f5b4b94.png)

**Comment by yuhuan-afk** [comment]
1.7.3?

**Comment by booxood** [comment]
1.7.3 之前默认配置的反向代理无法使用了，可以更新到最新版 or 在配置中指定可用的反向代理。
