### ISSUE TITLE
[Bug] 有無 "/" 號 差別

### ISSUE THREAD

**Issue by yuhuan-afk** [gitalk/gitalk#458]
#### Gitalk 版本
*1.7.2 (latest)*
#### 报错信息？
無，僅 bug
#### 浏览器版本？
Firefox 89.0.1 on Archlinux GNOME
#### 复现步骤？
無

網址列有無 *"/"* 號會影響留言結果
ex. 在
https://blog.nekohuan.cyou/2021/06/17/arch/
留的言無法在
https://blog.nekohuan.cyou/2021/06/17/arch
顯示，反之同理OAO

（*目前只能在同一個issue手動添加tag修復*，但麻煩，希望能改進
（或者等等可能提PR？不知道

總之如果可以希望盡快修復*～*

**Comment by yuhuan-afk** [comment]
＊discussion 同步

**Comment by booxood** [comment]
转移到 https://github.com/gitalk/gitalk/discussions/459 讨论吧~
