### ISSUE TITLE
响应状态 204，且 size 为 0B。

### ISSUE THREAD

**Issue by GanZhiXiong** [gitalk/gitalk#474]
#### Gitalk 版本
1.7.2

#### 报错信息？
![image](https://user-images.githubusercontent.com/27394631/130102076-19e245f1-d223-495e-bfbb-30a20d60e987.png)

#### 浏览器版本？
![image](https://user-images.githubusercontent.com/27394631/130102369-0c1e24d7-e160-4b85-8d51-6dbbabd341cd.png)

#### 复现步骤？
1. 打开 https://ganzhixiong.com/。
2. 打开 DevTools，点击 Network 选项。
3. 随便打开一篇文章。
4. Status 列按照从大到小排序。
5. 即可看到 gittalk 响应状态为 204，且 size 为 0B。

**Comment by lihugang** [comment]
http 204 no content 是缓存的状态码...
文件已经缓存了且未被更改
