### ISSUE TITLE
点击登录后显示404 File not found

### ISSUE THREAD

**Issue by mcthp** [gitalk/gitalk#492]
#### Gitalk 版本

 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
 <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>

#### 报错信息？

![image](https://user-images.githubusercontent.com/35915872/143475645-f2114c38-3fae-404f-a04c-1342cb3713a3.png)

#### 浏览器版本？

firefox 94.0.2
Edge 96.0.1054.34

#### 复现步骤？

![image](https://user-images.githubusercontent.com/35915872/143475571-491670e9-2034-4be7-817b-aa41a6890a18.png)
一点login就会显示报错(第一次点还会跳转至github的授权页,后来没了)
![image](https://user-images.githubusercontent.com/35915872/143475645-f2114c38-3fae-404f-a04c-1342cb3713a3.png)

**Comment by diamond-weiqu** [comment]
回调设置问题
