### ISSUE TITLE
想问一下，我这边做的评论，但是其中一条想要删除，不知道怎么操作

### ISSUE THREAD

**Issue by huangge1199** [gitalk/gitalk#496]
怎么实现删除功能

**Comment by dontknowhy** [comment]
既然基于issue
那把这个自动创建的issue关了应该就好了吧？

**Comment by xinqiaozero** [comment]
> 既然基于issue 那把这个自动创建的issue关了应该就好了吧？
直接关掉issue可以，但是不能隐藏评论（可能是gitalk的问题），只能删除或者关闭评论
