### ISSUE TITLE
未找到相关的 Issues 进行评论  请联系 @zelihole 初始化创建

### ISSUE THREAD

**Issue by zelihole** [gitalk/gitalk#552]
#### Gitalk 版本
最新

#### 报错信息？
未找到相关的 [Issues](https://github.com/zelihole/blogtalk/issues) 进行评论

请联系 @zelihole 初始化创建
#### 浏览器版本？
360浏览器（Chrome内核）
#### 复现步骤？
![img](https://i.ibb.co/fVRWF2g/20230628173137.png)
[https://zelihole.github.io/zelihole](https://zelihole.github.io/)

**Comment by gittyspirit** [comment]
只能通过科学上网登录Github账户方式解决，目前没有更好的办法

**Comment by zelihole** [comment]
> 只能通过科学上网登录Github账户方式解决，目前没有更好的办法

我可以正常（不用微皮恩）登录，就是加载不了QAQ

**Comment by gittyspirit** [comment]
应使用科学上网的方式登陆github账户，即使你可以正常登陆，也应使用科学上网的方式。否则无法初始化评论

**Comment by zelihole** [comment]
> 应使用科学上网的方式登陆github账户，即使你可以正常登陆，也应使用科学上网的方式。否则无法初始化评论

好吧 我逝逝

**Comment by zelihole** [comment]
(⊙o⊙)…

**Comment by gittyspirit** [comment]
为什么评论区还没设置好？还有什么问题吗

**Comment by HUIXwhy** [comment]
先登录后再初始化
以后的每个文章都要这样

**Comment by zelihole** [comment]
登录了，但是我用不了魔法，初始化不了QAQ

**Comment by HUIXwhy** [comment]
可以改代理
![image](https://github.com/gitalk/gitalk/assets/121380373/c94c7fc2-cf7e-4dd7-b85c-31e75f765fe7)
这个是我自己建的

**Comment by zelihole** [comment]
6我有空试试

**Comment by gittyspirit** [comment]
还是自己用cloudflare worker搭建Cors Anywhere放心

**Comment by mouday** [comment]
metoo

**Comment by huixpp** [comment]
> 还是自己用cloudflare worker搭建Cors Anywhere放心

可以自己搭的，vercel比worker快

**Comment by gittyspirit** [comment]
我不想贡献我的手机号。Worker还是能用的，自定义一下域名就可以了。https://www.spiritfr.eu.org/2023/08/29/%E5%A6%82%E4%BD%95%E5%9C%A8Cloudflare-worker%E4%B8%8A%E6%90%AD%E5%BB%BAcors-anywhere%E4%BB%A3%E7%90%86/
