### ISSUE TITLE
服务器炸了，该充钱了

### ISSUE THREAD

**Issue by lihan3238** [gitalk/gitalk#565]
#### Gitalk 版本
1.7.2
#### 报错信息？
![图片](https://github.com/gitalk/gitalk/assets/140466644/d5278e77-af0a-4b15-929e-b08c8c2971da)
```
已自动允许位于“https://lihan3238.github.io”上第一方隔离的“https://github.com”访问存储空间。 front-enddevelopmentroadmap

  APlayer v1.10.1 af84efb  http://aplayer.js.org 
APlayer.min.js:1:59096

  MetingJS v2.0.1  https://github.com/metowolf/MetingJS 
Meting.min.js:1:3145
源映射错误：Error: Invalid URL: webpack://[name]/webpack/universalModuleDefinition
源 URL：https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
源映射 URL：APlayer.min.js.map
已拦截跨源请求：同源策略禁止读取位于 https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。
已拦截跨源请求：同源策略禁止读取位于 https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token 的远程资源。（原因：CORS 请求未能成功）。状态码：(null)。
err:  Error: Network Error
    exports createError.js:16
    onerror xhr.js:83
gitalk.jsx:128:16
Error: Promised response from onMessage listener went out of scope init.js:79:27
```
#### 浏览器版本？
firefox 118.0.2 win11 x64
#### 复现步骤？
github登录gitalk即可。

**Comment by Muska-Ami** [comment]
建议自建 `cors-anywhere` ，这不是gitalk的问题吧
也可以试试我的 `https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token`

**Comment by lihan3238** [comment]
OK 感谢

**Comment by lz1219** [comment]
> 建议自建 `cors-anywhere` ，这不是gitalk的问题吧 也可以试试我的 `https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token`
> 
> 具体参考 `proxy` 配置项
感谢！

**Comment by hsh778205** [comment]
> 建议自建 `cors-anywhere` ，这不是gitalk的问题吧 也可以试试我的 `https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token`
> 
> 具体参考 `proxy` 配置项

@Muska-Ami 请问现在还能正常使用吗？我这边出现了Error：No access token

Hexo-Next主题，在gitalk.swig中添加了行`proxy: 'https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token',`

**Comment by Muska-Ami** [comment]
> > 建议自建 `cors-anywhere` ，这不是gitalk的问题吧 也可以试试我的 `https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token`
> > 
> > 具体参考 `proxy` 配置项
> 
> @Muska-Ami 请问现在还能正常使用吗？我这边出现了Error：No access token
> 
> Hexo-Next主题，在gitalk.swig中添加了行`proxy: 'https://cors-anywhere.1l1.icu/https://github.com/login/oauth/access_token',`

貌似GitHub API也出现了干扰，这个代理只能代理部分信息 我这边已经不行了，自行修改一下源码或者换一家评论插件吧 :D

**Comment by hsh778205** [comment]
@Muska-Ami 

好的，我已经成功配置了giscus了。[笔记](http://vanilla-chan.cn/blog/2024/06/18/Hexo-Blog-Next-Theme-Replacement-cdn/) 开心！
