### ISSUE TITLE
gitalk 对同一篇博文重复创建 issue

### ISSUE THREAD

**Issue by yingziwu** [gitalk/gitalk#68]
gitalk 会对同一篇博文创建多个tag。

例如： 对于[这篇博文](https://blog.bgme.me/posts/restructuredtext-test/)，管理员使用[小标题的链接]( https://blog.bgme.me/posts/restructuredtext-test/#id10)进入这篇博文，gitalk 会自动创建一个[新issure](https://github.com/yingziwu/yingziwu.github.io/issues/19)，而不是关联至[原有issue](https://github.com/yingziwu/yingziwu.github.io/issues/10)。如此则会重复创建issue，如 [#10](https://github.com/yingziwu/yingziwu.github.io/issues/10)、[#17](https://github.com/yingziwu/yingziwu.github.io/issues/17)、[#18](https://github.com/yingziwu/yingziwu.github.io/issues/18)、[#19](https://github.com/yingziwu/yingziwu.github.io/issues/19)。

非管理员使用[小标题的链接](https://blog.bgme.me/posts/restructuredtext-test/#id11)进入则会提示 `Related Issues not found`。

**Comment by newdee** [comment]
因为评论Issue的id有href和pathname两种，换成`location.pathname`就可以了
具体配置方法可参见[这个](https://newdee.cf/posts/4da30c7/)

**Comment by booxood** [comment]
没有新的疑问的话，先关闭了。
