### ISSUE TITLE
IE 下无法显示gitalk ，有解吗？

### ISSUE THREAD

**Issue by zxxwin** [gitalk/gitalk#69]
打开官网的demo，在最新的IE下都无法显示，其他浏览器（包括Edge）都正常。有解决办法不？

**Comment by booxood** [comment]
你的IE版本是多少？最新的IE应该是支持的。不兼容低版本的IE，主要是因为 Gitalk 是基于 Preact 的。

**Comment by xuchengpeng** [comment]
我的IE11貌似也无法显示，11不支持吗

**Comment by booxood** [comment]
@xuchengpeng @zxxwin 你们是报这个错吗？
![image](https://user-images.githubusercontent.com/2151410/33594895-c58b773a-d9d0-11e7-959a-b202332ea3f3.png)

**Comment by xuchengpeng** [comment]
@booxood  NexT主题我自己新增了gitalk的支持，chrome没问题，IE11下有这个错误

这一行gitalk.render('gitalk-container')报以下错误:
无法获取未定义或 null 引用的属性“resolve”

**Comment by xuchengpeng** [comment]
@booxood 
SCRIPT5007: 无法获取未定义或 null 引用的属性“resolve”
文件: gitalk.min.js，行: 12，列: 471

**Comment by booxood** [comment]
@zxxwin @xuchengpeng 试试 v1.2.0 ，应该修复了这个问题。

**Comment by booxood** [comment]
没反馈先不关闭了
