### ISSUE TITLE
提供方法修改 perPage 屬性

### ISSUE THREAD

**Issue by calpa** [gitalk/gitalk#7]
現在， perPage 屬性是在 [gitalk.jsx](https://github.com/gitalk/gitalk/blob/48de82ca24d4cb24a464f7cc9e72884a208b9d5c/src/gitalk.jsx#L56) 裡面的 constructor (第56行)構建的。

我想在構建gitalk之後，可以再次手動設置屬性 perPage 屬性，再次自行定義每個頁面的評論載入量。

- [ ] 提供 setPerPage(page: number) 方法

**Comment by booxood** [comment]
先关闭，PR 时直接关联就好。
