### ISSUE TITLE
缺乏开发环境文档说明

### ISSUE THREAD

**Issue by jimczj** [gitalk/gitalk#71]
要开发新功能的时候发现缺乏开发环境文档说明，希望在wiki上能补充

**Comment by booxood** [comment]
可以先把你的想法以 Issue 的形式提出来，然后提交 PR 参考 [这里 ](https://github.com/gitalk/gitalk/blob/master/readme-cn.md#贡献)。

`开发环境文档` 这块，有什么不明白的或者有什么可以参考的，可以直接先提出来，我后续补充完善。

**Comment by jimczj** [comment]
## 开发环境配置
1. 配置你的 Authorization callback URL
![image](https://user-images.githubusercontent.com/13499146/32741941-e215f65e-c8e2-11e7-835e-5a458fd5a3e2.png)

2.  在dev/index.js 文件下修改配置
![image](https://user-images.githubusercontent.com/13499146/32742048-361621de-c8e3-11e7-8332-8ca8d6cd50f6.png)

3. 修改webpack.config.js 的配置
![image](https://user-images.githubusercontent.com/13499146/32742128-65407d10-c8e3-11e7-939c-3fe4a9881669.png)

4. 运行命令 `npm run dev`

**Comment by booxood** [comment]
已添加到 [wiki/开发环境配置](https://github.com/gitalk/gitalk/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)
