### ISSUE TITLE
与require-2.1.6,jquery-1.9.1.min.js冲突，报错Error: Mismatched anonymous define() module:

### ISSUE THREAD

**Issue by cniter** [gitalk/gitalk#80]
我引用的是：<script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>，具体冲突的js文件为https://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js，
[Mismatched anonymous define() module](https://stackoverflow.com/questions/15371918/mismatched-anonymous-define-module)这里的解决方案是将冲突的js文件先引用，但由于我使用的主题的原因没办法做到这点，这还有其他的解决方法不？

**Comment by booxood** [comment]
Gitalk 应该不会跟 require.js 和 jQuery 冲突的，确定与 Gitalk 的引入位置有关系吗？

**Comment by cniter** [comment]
确实在https://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js 之前引用就能显示Gitalk，而在require-2.1.6,jquery-1.9.1.min.js之后引用就报提到的那个错，如果没办法的话就只能分开引用了，将gitalk.min.js，gitalk.css先引用，剩下的`var gitalk = new Gitalk...`后引用了╮(╯﹏╰）╭

**Comment by booxood** [comment]
@cniter 如果将`https://7.url.cn/edu/jslib/comb/require-2.1.6,jquery-1.9.1.min.js `放在前面引入，则采用 requirejs 的方式加载 Gitalk，例如

```js
require(['xxx/gitalk.min.js'], function (Gitalk) {
  var gitalk = new Gitalk(...)
  gitalk.render('gitalk-container')
})

```
