### ISSUE TITLE
在登录后如果注销再登录的话会报错  error: no access token

### ISSUE THREAD

**Issue by FeDemo** [gitalk/gitalk#81]
` error: no access token`
<br>
![](https://imgsa.baidu.com/forum/w%3D580%3B/sign=0604688aa7af2eddd4f149e1bd2b00e9/5d6034a85edf8db1bb1e6ae80223dd54564e740d.jpg)

**Comment by booxood** [comment]
> 登录后如果注销再登录

无法复现呢，还有其他信息可以提供吗？

**Comment by FeDemo** [comment]
使用火狐浏览器  ,F12浏览器的报错
```
res.data err: 
{…}
error: "bad_verification_code"
error_description: "The code passed is incorrect or expired."
error_uri: "https://developer.github.com/v3/oauth/#bad-verification-code"
__proto__: Object { … }
``` 
在[https://gitalk.github.io/](https://gitalk.github.io/)上和我的项目上都会发生
目前在手机上试验不会出现这情况,我先换个浏览器试试

**Comment by FeDemo** [comment]
更换360浏览器后没有出现该情况了....可能是本地Cookie的问题

**Comment by FeDemo** [comment]
![](https://imgsa.baidu.com/forum/w%3D580/sign=11efcbf8e0f81a4c2632ecc1e7286029/652a4fa7d933c895cc9fe1f7da1373f083020062.jpg)<br>
应该是请求太多频繁导致需要对**Github Application**重新授权

**Comment by tiexo** [comment]
我刚刚也遇到了...复现率很高
![tim 20180116215624](https://user-images.githubusercontent.com/8164505/34992674-da8813a6-fb08-11e7-820f-11c7c118293a.png)

**Comment by booxood** [comment]
先关闭 Issue，后续有疑问再打开。
