### ISSUE TITLE
在demo里点击github登录没有反应，自己的博客里点击登录就出错然后重定向了

### ISSUE THREAD

**Issue by Slzde** [gitalk/gitalk#83]
https://XXXXXXX/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by Slzde** [comment]
https://gitalk.github.io/  这里的demo点击 github登录没有任何反应，也没有任何加载

**Comment by Slzde** [comment]
自己的blog里点击登录就出现上面错误并重定向。
![sp171219_122748](https://user-images.githubusercontent.com/33687881/34140808-2911ff9e-e4b8-11e7-8e0e-dda0b1142e17.png)

**Comment by Slzde** [comment]
![sp171219_122852](https://user-images.githubusercontent.com/33687881/34140822-46d66e70-e4b8-11e7-9db9-92c0725f1775.png)
![sp171219_122630](https://user-images.githubusercontent.com/33687881/34140835-55988e52-e4b8-11e7-9815-d70d9125dff0.png)

**Comment by booxood** [comment]
> 自己的blog里点击登录就出现上面错误并重定向。

`出现上面的错误` 指的什么错误？

**Comment by booxood** [comment]
先关闭 Issue，后续有疑问再打开。
