### ISSUE TITLE
Ready add Russian translation

### ISSUE THREAD

**Issue by blinovartem** [gitalk/gitalk#86]
Hi, thanks for the interesting comments. Please add my translation Russian language

`{
  "init": "Gitalking ...",
  "no-found-related": "Связанные %{link} не найдены",
  "please-contact": "Пожалуйста, свяжитесь с  %{user}  чтобы инициализировать комментарий",
  "init-issue": "Выпуск инициализации",
  "leave-a-comment": "Оставить комментарий",
  "comment": "Комментарий",
  "support-markdown": "Поддерживается Markdown",
  "login-with-github": "Вход через Github",
  "first-comment-person": "Будьте первым, кто оставил комментарий",
  "commented": "прокомментированный",
  "load-more": "Загрузить ещё",
  "power": "%{link} v1.0.0",
  "counts": "%{counts} комментарий |||| %{counts} комментарьев",
  "sort-asc": "Сортировать по старым",
  "sort-desc": "Сортировать по последним",
  "logout": "Выход",
  "anonymous": "Анонимный"
}`

If there is a limit to the number of characters please email me to correct the translation

**Comment by booxood** [comment]
Released v1.2.2 support Russian.
