### ISSUE TITLE
【已解决】iOS上无法点击评论

### ISSUE THREAD

**Issue by xuchengpeng** [gitalk/gitalk#87]
使用的是hexo的NexT主题，在电脑上用Chrome或者Edge都可以正常使用gitalk，但是在iOS上，用safari或者chrome浏览器，点击 评论 按钮都没有反应，不知道什么原因。。。
https://xuchengpeng.github.io/guestbook/

**Comment by xuchengpeng** [comment]
更新到 [NexT 6.0](https://github.com/theme-next/hexo-theme-next) 后可以在ios上评论了

**Comment by booxood** [comment]
@xuchengpeng OK。可能元素样式上有冲突，按钮被遮了。
