### ISSUE TITLE
Error: Not Found.

### ISSUE THREAD

**Issue by dbsg** [gitalk/gitalk#88]
![wx20171229-172058](https://user-images.githubusercontent.com/32408876/34433812-b9e1e456-ecbc-11e7-86e6-c09a653c5a61.png)
![wx20171229-172044](https://user-images.githubusercontent.com/32408876/34433813-ba2c6e86-ecbc-11e7-9d76-131401a9b797.png)
![wx20171229-171948](https://user-images.githubusercontent.com/32408876/34433814-ba84e20a-ecbc-11e7-892f-1946699c512e.png)
![wx20171229-171854](https://user-images.githubusercontent.com/32408876/34433816-bb6c025c-ecbc-11e7-92e1-f6c7d396a52d.png)
![wx20171229-171824](https://user-images.githubusercontent.com/32408876/34433818-bbc60d10-ecbc-11e7-98c2-2c4e4fe61a1b.png)

**Comment by dbsg** [comment]
用hexo搭建博客的时候，不知道是否是gitalk配置出错，第一张图是点击评论时候的报错；第二张是初始化的时候的报错；最下面两张是配置。

**Comment by dbsg** [comment]
点击登录是可以的。

**Comment by xuchengpeng** [comment]
owner和admin填dbsg看看

**Comment by booxood** [comment]
@dbsg 上面两位同学已经解答了。

**Comment by dbsg** [comment]
好的，多谢各位。

**Comment by JackZhouMine** [comment]
> 好的，多谢各位。

请问你是怎么解决的呢？ 现在遇到这个问题

**Comment by JackZhouMine** [comment]
> > 好的，多谢各位。
> 
> 请问你是怎么解决的呢？ 现在遇到这个问题

谢谢 已经解决

**Comment by black-fruit** [comment]
我还是没有解决，上面的方法都用了。

**Comment by black-fruit** [comment]
```
啊啊啊啊啊
```

**Comment by booxood** [comment]
@black-fruit 配置发出来？
