### ISSUE TITLE
[需求]编辑器增加预览功能

### ISSUE THREAD

**Issue by bigmeow** [gitalk/gitalk#89]
github作为评论，使用者多是码农，在博客里代码交流比较多，现在虽然支持贴代码，但是不知道贴了后的排版是否正确，希望增加这个预览模式

**Comment by keveon** [comment]
如果能把 issue 的编辑框的功能搬过去就完美了

---

现在能力有限，帮不上忙，只能做一段时间的伸手党了……

**Comment by liolok** [comment]
@keveon GItment 的作者了解过了, 照搬 GitHub Issues 的样式是侵权的, 详见 Gitment 作者的[博文](https://imsun.net/posts/gitment-introduction/#%E6%A0%B7%E5%BC%8F%E7%89%88%E6%9D%83).
不过**预览**功能确实很需要, 希望开发团队能做这个增强.

**Comment by booxood** [comment]
@bigmeow @keveon @liolok v1.3.0 增加了预览

**Comment by liolok** [comment]
@booxood :clap::+1:
