### ISSUE TITLE
此项目是否抄袭 gitment ？

### ISSUE THREAD

**Issue by f2ex** [gitalk/gitalk#9]
gitment 项目地址： https://github.com/imsun/gitment

**Comment by mamboer** [comment]
@f2ex 
不知道你心中是如何定义抄袭的？
如果想法想象功能类似就算抄袭，那就：是的。
你也可以质疑preact抄袭react，weex抄袭react native，海尔抄格力，小米抄魅族~  我不敢苟同。
建议并欢迎你详细看看gitalk和gitment的代码，也欢迎别的同学帮忙回答这个问题。
**我的答案是：Gitalk是Gitment的竞品。**
Gitalk的出现是根本原因为了解决aotu.io多说评论不能用的问题，开源是无利益的奉献，是为了给大家分享我们觉得好用的值得分享的东西，帮助大家解决类似的问题。
希望同行能更多的正眼的Review两者的代码实现，学习不同的实现思路，或指正纰漏，或一起改进，少一点斜视。

**Comment by f2ex** [comment]
你想多了。这几天angular和vuejs撕*，我并不想在这发生这样的事。我尊重所有的开发者和开源项目。看到这个项目的功能和使用方法与gitment 极其相似。就尝试了解一下。标题中的“抄袭”换成“借鉴”或许更能表达我的意思。不过我想我已经知道答案了。

**Comment by chenglitao521** [comment]
算不算抄袭不重要，还不好用才重要

**Comment by linonetwo** [comment]
Gitment 都不更新了，赶紧换来这
