### ISSUE TITLE
[BUG],方法isElementAnSFC判断有问题，引发报错

### ISSUE THREAD

**Issue by bigmeow** [gitalk/gitalk#90]
**环境：**  vue-cli脚手架，编译后的生产环境
引入代码和官方的使用方法一致（es6 import语法），程序在开发环境正常运行，当用命令 npm run build构建后发布到生产环境后，点击评论或者展示评论列表时，代码报错
**使用代码：**
![image](https://user-images.githubusercontent.com/10484248/34453547-9f5c8fec-ed92-11e7-8e8e-629052ed9d9d.png)

**报错截图:**
![image](https://user-images.githubusercontent.com/10484248/34453569-0e0d98d2-ed93-11e7-9e1d-8ef1a012f5b7.png)

**跟踪错误到源码：**
![image](https://user-images.githubusercontent.com/10484248/34453604-5e8eaa1c-ed93-11e7-84fa-10afdae98e64.png)

发现这段代码有bug:
当 `element.type` 的值是undefined时，最后一行的 `element.type.prototype.isReactComponent`会报错；留意到该源码是react系的，我是在vue的单文件系统中引入的代码

最后，如果将代码直接以script的方法引入则没有任何问题

**Comment by booxood** [comment]
@bigmeow 应该是因为 vue 里 `this.$refs.comments` 获取到的元素 `typeof element.type === 'string'` 是 `false`，所以被认为是 React 组件。

你可以将 `this.$refs.comments` 换成原生 dom 元素试一下。

**Comment by xiongyizhu** [comment]
还是报错，我的是vue搭建的环境
![bug](https://user-images.githubusercontent.com/29998892/41126664-e1006e8a-6ada-11e8-86c4-198f834d86f1.png)

**Comment by booxood** [comment]
@xiongyizhu 贴下 Gitalk 的初始代码？

**Comment by bigmeow** [comment]
```js
gitalk.render(document.querySelector('.comment-wrap'))
```
换成原生dom

**Comment by xiongyizhu** [comment]
在localhost环境没有这个问题，部署到github pages的一个子页面中就有这个问题了
![bug1](https://user-images.githubusercontent.com/29998892/41157520-9155bace-6b58-11e8-9724-f98d1cf76dd7.png)

**Comment by xiongyizhu** [comment]
我解决是解决了，非常暴力的方法，把return  !element.type.prototype.isReactComponent直接改成了return true
但是为啥本地环境没有Cannot read property “prototype” of undefined

**Comment by sagittaria** [comment]
> ```js
> gitalk.render(document.querySelector('.comment-wrap'))
> ```
> 
> 换成原生dom

mark 明天再试，心累:cry:

**Comment by sagittaria** [comment]
> ```js
> gitalk.render(document.querySelector('.comment-wrap'))
> ```
> 
> 换成原生dom

emmm不行...最后也是强行
```
return element.type && element.type.prototype && !element.type.prototype.isReactComponent;
```

**Comment by xiaomingming** [comment]
找到老问题了。
