### ISSUE TITLE
能不能设置成自动创建Issues?

### ISSUE THREAD

**Issue by zhebinhu** [gitalk/gitalk#91]
rt

**Comment by xuchengpeng** [comment]
默认就是打开文章的时候自动创建issue啊

**Comment by booxood** [comment]
@zhebinhu 目前自带提供的方法就是像 @xuchengpeng  说的，默认打开文章时自动创建。

或者你也可以看一下这种办法（ [评论初始化](https://github.com/gitalk/gitalk/wiki/%E8%AF%84%E8%AE%BA%E5%88%9D%E5%A7%8B%E5%8C%96)）适不适合你。

**Comment by booxood** [comment]
先关闭 Issue，后续有疑问再打开。

**Comment by hiberabyss** [comment]
我的博客打开后没法自动创建对应的 issue. (https://hiberabyss.github.io/)

我是用的 `md5(window.location.pathname)` 作为 issue 的 id. 不知道这个会不会有影响.
谢谢!

**Comment by ripperhe** [comment]
@hiberabyss 我也出现了这个问题，登录报错，你解决了吗？

**Comment by booxood** [comment]
@hiberabyss `The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application`

访问的域名与配置的是一样的吗？

**Comment by ripperhe** [comment]
我发现我在申请app的那个页面填写的http ，但是我博客开启了https的，我在app的页面把域名改成了https就好了

**Comment by hiberabyss** [comment]
@ripperhe 嗯, 之前也是因为 http 和 https 不一致导致的问题. 在 Github 中改成强制 https 就好了.
