### ISSUE TITLE
关于产生重复issue的问题

### ISSUE THREAD

**Issue by yelog** [gitalk/gitalk#96]
刚才我测试了一下，进入页面后，先获取issue，如果没有，则会发起创建issue请求。

但是获取 issue 的请求并不是特别及时(好像在 github 端 有缓存)，就出现下面这种情况：

创建完成后，立即刷新页面，这时获取 issue 的请求并没有获取到刚刚创建的issue，则会进行重复创建。

面对这种情况要怎么处理？？？

**Comment by booxood** [comment]
谢谢这么详细说明的问题。

如果已经出现重复 issue 的情况，可以把重复的关掉只保留一个。

**Comment by booxood** [comment]
不知道在获取 issues 时带个时间戳什么的 可以不可以避免缓存，还需要验证。。

**Comment by yelog** [comment]
嗯，我做了一个`10分钟之内，不允许对同一个 pathname 发起多次创建 issue 的请求 ` 的约束，来**暂时**处理这种情况。

剩下的就是坐等大神你来解决问题了

**Comment by booxood** [comment]
发布了 v1.2.2，在获取 issue 时带了时间戳，应该可以屏蔽这种情况了。

**Comment by yelog** [comment]
刚测试了一下，没有问题了

**Comment by booxood** [comment]
感谢

**Comment by whorusq** [comment]
穿越了么，为啥现在还有这个问题呢？
