### ISSUE TITLE
Error: Not Found.

### ISSUE THREAD

**Issue by wenjundesign** [gitalk/gitalk#98]
能正常显示，可是评论不了，评论要存在哪里？能帮我看一下嘛？`https://wenjundesign.github.io/`

**Comment by booxood** [comment]
`repo` 配置的不对，需要配置为  github 的项目名

```js
var gitalk = new Gitalk({
  clientID: '179ed091ed7f9b0f90de',
  clientSecret: '633e911d74c0df0079fd4a1dc3de43e50940245a',
  repo: 'wenjundesign', -> 'wenjundesign.github.io'
  owner: 'wenjundesign',
  admin: ['wenjundesign'],
    language:'en',
})

gitalk.render('comment')
```

**Comment by appleyuchi** [comment]
@booxood 请问到底是
repo: 'wenjundesign'
还是
repo: 'wenjundesign.github.io'
呢？
谢谢

**Comment by timeflygo** [comment]
> @booxood 请问到底是
> repo: 'wenjundesign'
> 还是
> repo: 'wenjundesign.github.io'
> 呢？
> 谢谢

填写 repo: 'wenjundesign.github.io'
