### ISSUE TITLE
gitalk 现在挂了么 ? 

### ISSUE THREAD

**Issue by iShawnWang** [gitalk/gitalk#99]
访问 [https://gitalk.github.io](https://gitalk.github.io) 看 demo,  
下面有一行 : `Failed to load resource: the server responded with a status of 401 (Unauthorized)`

**Comment by booxood** [comment]
正常啊

出现 `Failed to load resource: the server responded with a status of 401 (Unauthorized)` 是因为没登录

**Comment by zhw2590582** [comment]
假如保存的token过期，就会返回401状态码，但代码里并没有这个拦截

**Comment by qcmoke** [comment]
请问这个问题怎么解决？
